import { v } from "convex/values";
import {
  internalMutation,
  mutation,
  query,
  type MutationCtx,
} from "./_generated/server.js";
import type { Doc, Id } from "./_generated/dataModel.js";
import { requireAdmin } from "./lib/authHelpers.js";
import { resolveTourImageUrls } from "./lib/resolveTourImages.js";

const FALLBACK_HERO =
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2000&q=80";

function locationMatchesTerms(location: string, terms: string[]): boolean {
  const l = location.toLowerCase();
  return terms.some((t) => t.length >= 2 && l.includes(t.toLowerCase()));
}

function slugifyLocation(loc: string): string {
  const first = loc.split(/[,·|]/)[0]?.trim() || loc.trim();
  const s = first
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72);
  return s || "destination";
}

function readableName(location: string): string {
  const first = location.split(/[,·|]/)[0]?.trim() || location.trim();
  return first.slice(0, 80) || "Destination";
}

function belongsToDestination(
  tour: Doc<"tours">,
  destination: Doc<"destinations">,
): boolean {
  if (Array.isArray(tour.destinationIds) && tour.destinationIds.length > 0) {
    return tour.destinationIds.some((id) => id === destination._id);
  }
  if (tour.destinationId) {
    return tour.destinationId === destination._id;
  }
  return locationMatchesTerms(tour.location, destination.matchTerms);
}

function matchTermsFromLocation(loc: string, slug: string): string[] {
  const terms = new Set<string>([slug.toLowerCase()]);
  for (const part of loc.toLowerCase().split(/[,·\s/|]+/)) {
    const p = part.trim();
    if (p.length >= 3) terms.add(p);
  }
  terms.add(slugifyLocation(loc));
  return Array.from(terms);
}

function primaryVisualFromImages(images: string[]): {
  heroStorageId?: Id<"_storage">;
  heroExternalUrl?: string;
} {
  for (const r of images) {
    const t = r.trim();
    if (!t) continue;
    if (/^https?:\/\//i.test(t)) return { heroExternalUrl: t };
    if (t.startsWith("/")) return { heroExternalUrl: t };
    return { heroStorageId: t as Id<"_storage"> };
  }
  return {};
}

export async function resolveDestinationHeroUrl(
  ctx: { storage: { getUrl: (id: Id<"_storage">) => Promise<string | null> } },
  d: Doc<"destinations">,
): Promise<string> {
  if (d.heroStorageId) {
    const u = await ctx.storage.getUrl(d.heroStorageId);
    if (u) return u;
  }
  if (d.heroExternalUrl) return d.heroExternalUrl;
  return FALLBACK_HERO;
}

async function ensureUniqueSlug(ctx: MutationCtx, base: string): Promise<string> {
  let slug = base;
  let n = 0;
  for (;;) {
    const existing = await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q) => q.eq("slug", slug))
      .unique();
    if (!existing) return slug;
    n += 1;
    slug = `${base}-${n}`;
  }
}

type DestinationSeedRow = Omit<
  Doc<"destinations">,
  "_id" | "_creationTime" | "createdAt" | "updatedAt"
>;

const DEFAULT_DESTINATIONS: DestinationSeedRow[] = [
  {
    slug: "hunza",
    name: "Hunza",
    line: "Karakoram classics and fort towns.",
    description:
      "Hunza Valley is the crown jewel of the Karakoram Highway — terraced villages, historic forts, and unobstructed views of Rakaposhi and Ultar Sar.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["hunza", "karimabad", "nagar", "aliabad", "eagle"],
    bestTime:
      "Late April through October for stable roads and clear skies. Spring blossoms and autumn colors are ideal.",
    tips: [
      "Acclimatize in Gilgit or Karimabad before aggressive hikes.",
      "Carry layers — mountain weather shifts fast even in summer.",
      "Book transport early for Naltar and Khunjerab add-ons.",
    ],
    costEstimate:
      "Budget trips often start around PKR 45k–70k per person for shorter road packages; mid-range with private jeep and better stays typically PKR 90k–150k+ depending on group size.",
    bullets: [
      "Mix culture stops with day hikes to Eagle’s Nest.",
      "Pair with Khunjerab Pass or Naltar for a longer northern loop.",
    ],
    autoGenerated: false,
    sortOrder: 0,
  },
  {
    slug: "skardu",
    name: "Skardu",
    line: "Lakes, Deosai, and high peaks.",
    description:
      "Skardu sits at the heart of Baltistan — the launch point for Shangrila, Upper Kachura Lake, Deosai Plains, and serious trekking toward some of the world’s highest peaks.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["skardu", "shigar", "kachura", "deosai", "khaplu"],
    bestTime:
      "May–October for road access to lakes and Deosai; confirm flight and road status in shoulder seasons.",
    tips: [
      "Buffer 1–2 days for domestic flight delays from Islamabad.",
      "Deosai requires a full day — start early and carry wind protection.",
    ],
    costEstimate:
      "Road-and-lake itineraries often range PKR 55k–95k per person on shared packages; private jeep + upgraded lodging toward PKR 120k–200k+.",
    bullets: [
      "Ideal for lake hopping and jeep safaris when roads are open.",
      "Add Deosai for wildlife and wide high-altitude plains.",
    ],
    autoGenerated: false,
    sortOrder: 1,
  },
  {
    slug: "swat",
    name: "Swat",
    line: "Green valleys and heritage.",
    description:
      "Swat offers greener alpine scenery, river valleys, and Buddhist heritage — often easier logistics than far-north circuits while still feeling remote.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["swat", "mingora", "malam jabba", "kalam"],
    bestTime:
      "March–November for valley touring; Malam Jabba ski season runs winter with different packing.",
    tips: [
      "Combine cultural stops in Mingora with upper-valley viewpoints.",
      "Check monsoon advisories for riverside routes in July–August.",
    ],
    costEstimate:
      "Shorter Swat circuits can start near PKR 35k–60k per person; extended luxury packages scale with transport.",
    bullets: [
      "Great for shorter trips when time is tight.",
      "Combine Malam Jabba, Bahrain, and upper valley viewpoints.",
    ],
    autoGenerated: false,
    sortOrder: 2,
  },
  {
    slug: "naran",
    name: "Naran",
    line: "Saif-ul-Malook and Babusar.",
    description:
      "Naran and Kaghan are classic road-trip territory — Saif-ul-Malook, Lulusar Lake, and the Babusar Pass link toward Gilgit-Baltistan.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["naran", "kaghan", "saif", "babusar", "shogran"],
    bestTime:
      "June–September for Babusar access; winter closures apply — verify pass status before locking dates.",
    tips: [
      "Lake Saif-ul-Malook jeeps fill fast — depart early morning.",
      "Pair with Hunza by road when Babusar is open for a longer loop.",
    ],
    costEstimate:
      "Weekend Naran–Shogran packages often fall PKR 25k–55k per person depending on transport and hotel tier.",
    bullets: [
      "Peak season is summer; Babusar may close outside favorable months.",
      "Works well as a stepping stone toward Hunza or Skardu.",
    ],
    autoGenerated: false,
    sortOrder: 3,
  },
];

export const seedDefaults = mutation({
  args: {},
  handler: async (ctx) => {
    await requireAdmin(ctx);
    const any = await ctx.db.query("destinations").take(1);
    if (any.length > 0) return { inserted: 0, skipped: true as const };
    const now = Date.now();
    let inserted = 0;
    for (const row of DEFAULT_DESTINATIONS) {
      await ctx.db.insert("destinations", {
        ...row,
        createdAt: now,
        updatedAt: now,
      });
      inserted++;
    }
    return { inserted, skipped: false as const };
  },
});

export const listForTourAssignment = query({
  args: {},
  handler: async (ctx) => {
    const rows = await ctx.db.query("destinations").collect();
    return rows
      .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
      .map((d) => ({
        _id: d._id,
        name: d.name,
        slug: d.slug,
      }));
  },
});

export const listForAdmin = query({
  args: {},
  handler: async (ctx) => {
    await requireAdmin(ctx);
    const rows = await ctx.db.query("destinations").collect();
    const tours = await ctx.db.query("tours").collect();
    return Promise.all(
      rows
        .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
        .map(async (d) => ({
          ...d,
          heroUrl: await resolveDestinationHeroUrl(ctx, d),
          tourCount: tours.filter((t) => t.isActive && belongsToDestination(t, d)).length,
        })),
    );
  },
});

export const createDestination = mutation({
  args: {
    name: v.string(),
    slug: v.optional(v.string()),
    line: v.string(),
    description: v.string(),
    heroExternalUrl: v.optional(v.string()),
    matchTerms: v.array(v.string()),
    bestTime: v.string(),
    tips: v.array(v.string()),
    costEstimate: v.string(),
    bullets: v.array(v.string()),
    sortOrder: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    await requireAdmin(ctx);
    const now = Date.now();
    const base = (args.slug?.trim() || slugifyLocation(args.name)).toLowerCase();
    const slug = await ensureUniqueSlug(ctx, base);
    return await ctx.db.insert("destinations", {
      slug,
      name: args.name.trim(),
      line: args.line.trim(),
      description: args.description.trim(),
      heroExternalUrl: args.heroExternalUrl?.trim() || undefined,
      matchTerms: args.matchTerms.map((t) => t.trim().toLowerCase()).filter(Boolean),
      bestTime: args.bestTime.trim(),
      tips: args.tips.map((t) => t.trim()).filter(Boolean),
      costEstimate: args.costEstimate.trim(),
      bullets: args.bullets.map((b) => b.trim()).filter(Boolean),
      autoGenerated: false,
      sortOrder: args.sortOrder ?? 100,
      createdAt: now,
      updatedAt: now,
    });
  },
});

export const updateDestination = mutation({
  args: {
    destinationId: v.id("destinations"),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    line: v.optional(v.string()),
    description: v.optional(v.string()),
    heroExternalUrl: v.optional(v.string()),
    matchTerms: v.optional(v.array(v.string())),
    bestTime: v.optional(v.string()),
    tips: v.optional(v.array(v.string())),
    costEstimate: v.optional(v.string()),
    bullets: v.optional(v.array(v.string())),
    sortOrder: v.optional(v.number()),
  },
  handler: async (ctx, { destinationId, ...patch }) => {
    await requireAdmin(ctx);
    const existing = await ctx.db.get(destinationId);
    if (!existing) throw new Error("Destination not found");

    const next: Record<string, unknown> = {};
    for (const [k, val] of Object.entries(patch)) {
      if (val !== undefined) next[k] = val;
    }

    if (typeof next.slug === "string") {
      const normalized = String(next.slug).trim().toLowerCase();
      if (normalized && normalized !== existing.slug) {
        const conflict = await ctx.db
          .query("destinations")
          .withIndex("by_slug", (q) => q.eq("slug", normalized))
          .unique();
        if (conflict && conflict._id !== destinationId) {
          throw new Error("Slug already exists");
        }
      }
      next.slug = normalized;
    }

    if (Array.isArray(next.matchTerms)) {
      next.matchTerms = (next.matchTerms as string[])
        .map((t) => t.trim().toLowerCase())
        .filter(Boolean);
    }
    if (Array.isArray(next.tips)) {
      next.tips = (next.tips as string[]).map((t) => t.trim()).filter(Boolean);
    }
    if (Array.isArray(next.bullets)) {
      next.bullets = (next.bullets as string[]).map((b) => b.trim()).filter(Boolean);
    }

    next.updatedAt = Date.now();

    await ctx.db.patch(
      destinationId,
      next as Partial<Omit<Doc<"destinations">, "_id" | "_creationTime">>,
    );
  },
});

export const deleteDestination = mutation({
  args: { destinationId: v.id("destinations") },
  handler: async (ctx, { destinationId }) => {
    await requireAdmin(ctx);
    const tours = await ctx.db.query("tours").collect();
    for (const t of tours) {
      const nextDestinationIds = Array.isArray(t.destinationIds)
        ? t.destinationIds.filter((id) => id !== destinationId)
        : undefined;
      const patch: Record<string, unknown> = {};
      if (t.destinationId === destinationId) {
        patch.destinationId = undefined;
      }
      if (Array.isArray(t.destinationIds) && t.destinationIds.includes(destinationId)) {
        patch.destinationIds = nextDestinationIds;
      }
      if (Object.keys(patch).length > 0) {
        await ctx.db.patch(t._id, patch as Partial<Doc<"tours">>);
      }
    }
    await ctx.db.delete(destinationId);
  },
});

export const syncFromTour = internalMutation({
  args: { tourId: v.id("tours") },
  handler: async (ctx, { tourId }) => {
    const tour = await ctx.db.get(tourId);
    if (!tour || !tour.isActive) return;

    const dests = await ctx.db.query("destinations").collect();
    const primary = primaryVisualFromImages(tour.images);
    const now = Date.now();
    const assignedDestinationIds = [
      ...(Array.isArray(tour.destinationIds) ? tour.destinationIds : []),
      ...(tour.destinationId ? [tour.destinationId] : []),
    ];

    if (assignedDestinationIds.length > 0) {
      const uniqueAssigned = Array.from(new Set(assignedDestinationIds));
      for (const destinationId of uniqueAssigned) {
        const assigned = await ctx.db.get(destinationId);
        if (!assigned) continue;
        const shouldSetHero =
          assigned.autoGenerated ||
          (!assigned.heroStorageId && !assigned.heroExternalUrl);
        if (shouldSetHero) {
          await ctx.db.patch(assigned._id, {
            ...primary,
            updatedAt: now,
          });
        }
      }
      return;
    }

    const matched = dests.filter((d) =>
      locationMatchesTerms(tour.location, d.matchTerms),
    );

    if (matched.length > 0) {
      for (const d of matched) {
        const shouldSetHero =
          d.autoGenerated ||
          (!d.heroStorageId && !d.heroExternalUrl);
        if (!shouldSetHero) continue;
        await ctx.db.patch(d._id, {
          ...primary,
          updatedAt: now,
        });
      }
      return;
    }

    const base = slugifyLocation(tour.location);
    const slug = await ensureUniqueSlug(ctx, base);
    await ctx.db.insert("destinations", {
      slug,
      name: readableName(tour.location),
      line: "Tours and experiences in this region.",
      description: `Browse active tours and packages covering ${tour.location}.`,
      matchTerms: matchTermsFromLocation(tour.location, slug),
      bestTime:
        "Contact us for the best seasonal windows and road status for this area.",
      tips: [
        "Book transport and stays early in peak season.",
        "Confirm road and pass status before travel.",
      ],
      costEstimate:
        "Pricing varies by group size and inclusions — see individual tours in this region.",
      bullets: [
        "Hand-picked routes from our catalog.",
        "Combine with nearby regions for longer trips.",
      ],
      autoGenerated: true,
      sortOrder: 1000,
      createdAt: now,
      updatedAt: now,
      ...primary,
    });
  },
});

export const listForIndex = query({
  args: {},
  handler: async (ctx) => {
    const dests = await ctx.db.query("destinations").collect();
    if (dests.length === 0) return [];
    const active = await ctx.db
      .query("tours")
      .withIndex("by_isActive", (q) => q.eq("isActive", true))
      .take(500);
    const sorted = dests.sort(
      (a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name),
    );
    return Promise.all(
      sorted.map(async (d) => {
        const matched = active.filter((t) =>
          belongsToDestination(t, d),
        );
        const heroUrl = await resolveDestinationHeroUrl(ctx, d);
        const preview = await Promise.all(
          matched.slice(0, 3).map(async (t) => ({
            slug: t.slug,
            title: t.title,
            price: t.price,
            images: await resolveTourImageUrls(ctx, t.images),
          })),
        );
        return {
          slug: d.slug,
          name: d.name,
          line: d.line,
          heroUrl,
          tourCount: matched.length,
          previewTours: preview,
          moreCount: Math.max(0, matched.length - 3),
        };
      }),
    );
  },
});

export const getPublicBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const d = await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q) => q.eq("slug", slug))
      .unique();
    if (!d) return null;
    const heroUrl = await resolveDestinationHeroUrl(ctx, d);
    return {
      slug: d.slug,
      name: d.name,
      line: d.line,
      description: d.description,
      heroUrl,
      bestTime: d.bestTime,
      tips: d.tips,
      costEstimate: d.costEstimate,
      bullets: d.bullets,
      matchTerms: d.matchTerms,
    };
  },
});

export const listSlugs = query({
  args: {},
  handler: async (ctx) => {
    const dests = await ctx.db.query("destinations").collect();
    return dests.map((d) => d.slug);
  },
});

export const listRelatedTours = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const d = await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q) => q.eq("slug", slug))
      .unique();
    if (!d) return [];
    const tours = await ctx.db.query("tours").collect();
    const matched = tours.filter(
      (t) =>
        t.isActive && belongsToDestination(t, d),
    );
    return Promise.all(
      matched.slice(0, 12).map(async (t) => ({
        slug: t.slug,
        title: t.title,
        description: t.description,
        price: t.price,
        durationDays: t.durationDays,
        location: t.location,
        images: await resolveTourImageUrls(ctx, t.images),
      })),
    );
  },
});

export const bulkUpsert = mutation({
  args: {
    rows: v.array(
      v.object({
        slug: v.optional(v.string()),
        name: v.string(),
        line: v.string(),
        description: v.string(),
        heroExternalUrl: v.optional(v.string()),
        matchTerms: v.array(v.string()),
        bestTime: v.string(),
        tips: v.array(v.string()),
        costEstimate: v.string(),
        bullets: v.array(v.string()),
        sortOrder: v.optional(v.number()),
      }),
    ),
  },
  handler: async (ctx, { rows }) => {
    const admin = await requireAdmin(ctx);
    const now = Date.now();
    let created = 0;
    let updated = 0;
    let skipped = 0;
    const errors: Array<{ index: number; message: string }> = [];

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i]!;
      try {
        const base = (row.slug?.trim() || slugifyLocation(row.name)).toLowerCase();
        if (!row.name.trim()) throw new Error("name is required");
        if (!row.line.trim()) throw new Error("line is required");
        if (!row.description.trim()) throw new Error("description is required");
        if (!row.bestTime.trim()) throw new Error("bestTime is required");
        if (!row.costEstimate.trim()) throw new Error("costEstimate is required");

        const normalizedSlug = base;
        const existing = await ctx.db
          .query("destinations")
          .withIndex("by_slug", (q) => q.eq("slug", normalizedSlug))
          .unique();

        const payload = {
          slug: normalizedSlug,
          name: row.name.trim(),
          line: row.line.trim(),
          description: row.description.trim(),
          heroExternalUrl: row.heroExternalUrl?.trim() || undefined,
          matchTerms: row.matchTerms.map((t) => t.trim().toLowerCase()).filter(Boolean),
          bestTime: row.bestTime.trim(),
          tips: row.tips.map((t) => t.trim()).filter(Boolean),
          costEstimate: row.costEstimate.trim(),
          bullets: row.bullets.map((b) => b.trim()).filter(Boolean),
          sortOrder: row.sortOrder ?? 100,
          updatedAt: now + i,
        };

        if (existing) {
          await ctx.db.patch(existing._id, payload);
          updated++;
        } else {
          const slug = await ensureUniqueSlug(ctx, normalizedSlug);
          await ctx.db.insert("destinations", {
            ...payload,
            slug,
            autoGenerated: false,
            createdAt: now + i,
          });
          created++;
        }
      } catch (e) {
        errors.push({ index: i, message: e instanceof Error ? e.message : String(e) });
        skipped++;
      }
    }

    await ctx.db.insert("adminLogs", {
      action: "bulk_upsert_destinations",
      performedBy: admin._id,
      timestamp: Date.now(),
      details: `processed=${rows.length} created=${created} updated=${updated} skipped=${skipped}`,
    });

    return { processed: rows.length, created, updated, skipped, errors };
  },
});
