import { v } from "convex/values";
import {
  internalMutation,
  internalQuery,
  mutation,
  query,
  type MutationCtx,
  type QueryCtx,
} from "./_generated/server.js";
import { internal } from "./_generated/api.js";
import type { Doc, Id } from "./_generated/dataModel.js";
import { requireAdminFromSession } from "./lib/authHelpers.js";
import { resolveTourImageUrls } from "./lib/resolveTourImages.js";

const FALLBACK_HERO =
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2000&q=80";

function locationMatchesTerms(location: string, terms: string[]): boolean {
  const l = location.toLowerCase();
  return terms.some((t) => t.length >= 2 && l.includes(t.toLowerCase()));
}

function slugifyLocation(loc: string): string {
  const first = loc.split(/[,·|]/)[0]?.trim() || loc.trim();
  const s = first
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72);
  return s || "destination";
}

function readableName(location: string): string {
  const first = location.split(/[,·|]/)[0]?.trim() || location.trim();
  return first.slice(0, 80) || "Destination";
}

function belongsToDestination(
  tour: Doc<"tours">,
  destination: Doc<"destinations">,
): boolean {
  if (Array.isArray(tour.destinationIds) && tour.destinationIds.length > 0) {
    return tour.destinationIds.some((id) => id === destination._id);
  }
  if (tour.destinationId) {
    return tour.destinationId === destination._id;
  }
  return locationMatchesTerms(tour.location, destination.matchTerms);
}

function matchTermsFromLocation(loc: string, slug: string): string[] {
  const terms = new Set<string>([slug.toLowerCase()]);
  for (const part of loc.toLowerCase().split(/[,·\s/|]+/)) {
    const p = part.trim();
    if (p.length >= 3) terms.add(p);
  }
  terms.add(slugifyLocation(loc));
  return Array.from(terms);
}

function primaryVisualFromImages(images: string[]): {
  heroStorageId?: Id<"_storage">;
  heroExternalUrl?: string;
} {
  for (const r of images) {
    const t = r.trim();
    if (!t) continue;
    if (/^https?:\/\//i.test(t)) return { heroExternalUrl: t };
    if (t.startsWith("/")) return { heroExternalUrl: t };
    return { heroStorageId: t as Id<"_storage"> };
  }
  return {};
}

export async function resolveDestinationHeroUrl(
  ctx: { storage: { getUrl: (id: Id<"_storage">) => Promise<string | null> } },
  d: Doc<"destinations">,
): Promise<string> {
  if (d.heroStorageId) {
    const u = await ctx.storage.getUrl(d.heroStorageId);
    if (u) return u;
  }
  if (d.heroExternalUrl) return d.heroExternalUrl;
  return FALLBACK_HERO;
}

/** Slug lookup without `.unique()`, so an existing duplicate can't crash a page. */
async function findDestinationBySlug(
  ctx: QueryCtx | MutationCtx,
  slug: string,
): Promise<Doc<"destinations"> | null> {
  return await ctx.db
    .query("destinations")
    .withIndex("by_slug", (q) => q.eq("slug", slug))
    .first();
}

async function ensureUniqueSlug(ctx: MutationCtx, base: string): Promise<string> {
  let slug = base;
  let n = 0;
  for (;;) {
    const existing = await findDestinationBySlug(ctx, slug);
    if (!existing) return slug;
    n += 1;
    slug = `${base}-${n}`;
  }
}

type DestinationSeedRow = Omit<
  Doc<"destinations">,
  "_id" | "_creationTime" | "createdAt" | "updatedAt"
>;

const DEFAULT_DESTINATIONS: DestinationSeedRow[] = [
  {
    slug: "lahore",
    name: "Lahore",
    line: "Mughal heartland & Walled City.",
    description:
      "Lahore is Pakistan's cultural capital — Mughal masterpieces at Badshahi Mosque and Lahore Fort, labyrinthine Walled City lanes, and food streets that define Punjabi hospitality.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["lahore", "walled city", "badshahi", "shalimar", "fort road"],
    bestTime:
      "October–March for comfortable walking tours; spring for festivals and mild weather.",
    tips: [
      "Start early at Lahore Fort before crowds build.",
      "Wear modest dress for mosque and shrine visits.",
    ],
    costEstimate:
      "Weekend heritage packages often start PKR 25k–45k per person; private guides push toward PKR 60k–90k+.",
    bullets: [
      "Pair Badshahi Mosque with an old-city food trail.",
      "Add Shalimar Gardens for a longer Punjab circuit.",
    ],
    autoGenerated: false,
    provinceSlug: "punjab",
    sortOrder: 0,
  },
  {
    slug: "multan",
    name: "Multan",
    line: "Shrines, tilework & Sufi heritage.",
    description:
      "Multan — the City of Saints — blends blue-tile shrines, Sufi traditions, and centuries of craft heritage in south Punjab.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["multan", "shrines", "ghanta ghar"],
    bestTime: "November–February for pleasant daytime walks.",
    tips: [
      "Dress modestly at shrines and remove shoes where required.",
      "Combine with Lahore for a full Punjab heritage loop.",
    ],
    costEstimate: "Short Multan circuits often range PKR 20k–40k per person.",
    bullets: [
      "Focus on shrine architecture and old-city bazaars.",
      "Pair with Lahore for Mughal + Sufi contrast.",
    ],
    autoGenerated: false,
    provinceSlug: "punjab",
    sortOrder: 1,
  },
  {
    slug: "taxila",
    name: "Taxila",
    line: "Gandhara archaeology & museums.",
    description:
      "Taxila preserves Gandhara civilization — Buddhist stupas, archaeological ruins, and museum collections just outside Islamabad.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["taxila", "gandhara", "museum"],
    bestTime: "October–April for comfortable site walks.",
    tips: [
      "Hire a licensed guide to interpret archaeological sites.",
      "Pair with Swat for a longer Buddhist heritage trail.",
    ],
    costEstimate: "Day trips from Islamabad often start PKR 15k–30k per person.",
    bullets: [
      "Ideal as a day trip from Islamabad or Rawalpindi.",
      "Combine with Swat for Gandhara-focused itineraries.",
    ],
    autoGenerated: false,
    provinceSlug: "islamabad",
    sortOrder: 2,
  },
  {
    slug: "chitral",
    name: "Chitral",
    line: "Kalash valleys & living traditions.",
    description:
      "Chitral opens onto the Kalash valleys — one of Pakistan's most distinctive living cultures, with valley drives and local festivals.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["chitral", "kalash", "bumburet", "runder"],
    bestTime: "May–October for valley access; plan around Kalash festivals.",
    tips: [
      "Respect Kalash customs — ask before photographing people or rituals.",
      "Buffer extra days for road conditions.",
    ],
    costEstimate:
      "Chitral–Kalash packages often range PKR 80k–150k+ per person.",
    bullets: [
      "Culture-first itinerary with Chitral town and Kalash villages.",
      "Combine with Swat or Hunza for a longer north circuit.",
    ],
    autoGenerated: false,
    provinceSlug: "kpk",
    sortOrder: 3,
  },
  {
    slug: "hunza",
    name: "Hunza",
    line: "Ancient forts & Karakoram culture.",
    description:
      "Hunza Valley pairs 700-year-old Baltit and Altit forts with terraced villages, apricot culture, and unobstructed Karakoram views.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["hunza", "karimabad", "nagar", "aliabad", "eagle", "baltit", "altit"],
    bestTime:
      "Late April through October for stable roads and clear skies. Spring blossoms and autumn colors are ideal.",
    tips: [
      "Acclimatize in Gilgit or Karimabad before aggressive hikes.",
      "Carry layers — mountain weather shifts fast even in summer.",
      "Book transport early for Naltar and Khunjerab add-ons.",
    ],
    costEstimate:
      "Budget trips often start around PKR 45k–70k per person for shorter road packages; mid-range with private jeep and better stays typically PKR 90k–150k+ depending on group size.",
    bullets: [
      "Mix culture stops with day hikes to Eagle’s Nest.",
      "Pair with Khunjerab Pass or Naltar for a longer northern loop.",
    ],
    autoGenerated: false,
    provinceSlug: "gilgit-baltistan",
    sortOrder: 4,
  },
  {
    slug: "skardu",
    name: "Skardu",
    line: "Royal forts, Silk Route & lakes.",
    description:
      "Skardu blends Silk Route heritage — Shigar Fort, Khaplu Palace — with surreal lakes and Karakoram scenery at the heart of Baltistan.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["skardu", "shigar", "kachura", "deosai", "khaplu"],
    bestTime:
      "May–October for road access to lakes and Deosai; confirm flight and road status in shoulder seasons.",
    tips: [
      "Buffer 1–2 days for domestic flight delays from Islamabad.",
      "Deosai requires a full day — start early and carry wind protection.",
    ],
    costEstimate:
      "Road-and-lake itineraries often range PKR 55k–95k per person on shared packages; private jeep + upgraded lodging toward PKR 120k–200k+.",
    bullets: [
      "Ideal for lake hopping and jeep safaris when roads are open.",
      "Add Deosai for wildlife and wide high-altitude plains.",
    ],
    autoGenerated: false,
    provinceSlug: "gilgit-baltistan",
    sortOrder: 5,
  },
  {
    slug: "swat",
    name: "Swat",
    line: "Gandhara heritage & emerald valleys.",
    description:
      "Swat leads with Buddhist Gandhara heritage and archaeological sites, then opens into greener alpine valleys.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["swat", "mingora", "malam jabba", "kalam", "buddhist"],
    bestTime:
      "March–November for valley touring; Malam Jabba ski season runs winter with different packing.",
    tips: [
      "Combine cultural stops in Mingora with upper-valley viewpoints.",
      "Check monsoon advisories for riverside routes in July–August.",
    ],
    costEstimate:
      "Shorter Swat circuits can start near PKR 35k–60k per person; extended luxury packages scale with transport.",
    bullets: [
      "Great for shorter trips when time is tight.",
      "Combine Malam Jabba, Bahrain, and upper valley viewpoints.",
    ],
    autoGenerated: false,
    provinceSlug: "kpk",
    sortOrder: 6,
  },
  {
    slug: "naran",
    name: "Naran",
    line: "Lake legends & highland culture.",
    description:
      "Naran and Kaghan carry Mughal-era lake legends around Saif-ul-Malook, highland culture, and the Babusar route.",
    heroExternalUrl:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80",
    matchTerms: ["naran", "kaghan", "saif", "babusar", "shogran"],
    bestTime:
      "June–September for Babusar access; winter closures apply — verify pass status before locking dates.",
    tips: [
      "Lake Saif-ul-Malook jeeps fill fast — depart early morning.",
      "Pair with Hunza by road when Babusar is open for a longer loop.",
    ],
    costEstimate:
      "Weekend Naran–Shogran packages often fall PKR 25k–55k per person depending on transport and hotel tier.",
    bullets: [
      "Peak season is summer; Babusar may close outside favorable months.",
      "Works well as a stepping stone toward Hunza or Skardu.",
    ],
    autoGenerated: false,
    provinceSlug: "kpk",
    sortOrder: 7,
  },
];

export const seedDefaults = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const any = await ctx.db.query("destinations").take(1);
    if (any.length > 0) return { inserted: 0, skipped: true as const };
    const now = Date.now();
    let inserted = 0;
    for (const row of DEFAULT_DESTINATIONS) {
      await ctx.db.insert("destinations", {
        ...row,
        createdAt: now,
        updatedAt: now,
      });
      inserted++;
    }
    return { inserted, skipped: false as const };
  },
});

/**
 * Adds any missing culture + heritage default destinations by slug.
 *
 * Insert-only: an existing destination (default or admin-edited) is never
 * overwritten — this used to reset admin-written copy, heroes and sort order.
 * `updated` is kept in the return shape for compatibility and is always 0.
 */
export const syncDefaultCatalog = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const now = Date.now();
    let created = 0;
    for (let i = 0; i < DEFAULT_DESTINATIONS.length; i++) {
      const row = DEFAULT_DESTINATIONS[i]!;
      const existing = await findDestinationBySlug(ctx, row.slug);
      if (existing) continue;
      await ctx.db.insert("destinations", {
        ...row,
        autoGenerated: false,
        createdAt: now + i,
        updatedAt: now + i,
      });
      created++;
    }
    return { created, updated: 0, total: DEFAULT_DESTINATIONS.length };
  },
});

export const listForTourAssignment = query({
  args: {},
  handler: async (ctx) => {
    const rows = await ctx.db.query("destinations").collect();
    return rows
      .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
      .map((d) => ({
        _id: d._id,
        name: d.name,
        slug: d.slug,
      }));
  },
});

export const listForAdmin = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const rows = await ctx.db.query("destinations").collect();
    const tours = await ctx.db.query("tours").collect();
    return Promise.all(
      rows
        .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
        .map(async (d) => ({
          ...d,
          heroUrl: await resolveDestinationHeroUrl(ctx, d),
          tourCount: tours.filter((t) => t.isActive && belongsToDestination(t, d)).length,
        })),
    );
  },
});

/** Convex upload URL for a destination hero image — POST the file, use returned `storageId`. */
export const generateDestinationHeroUploadUrl = mutation({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    await requireAdminFromSession(ctx, sessionToken);
    return await ctx.storage.generateUploadUrl();
  },
});

export const createDestination = mutation({
  args: {
    sessionToken: v.string(),
    name: v.string(),
    slug: v.optional(v.string()),
    line: v.string(),
    description: v.string(),
    heroStorageId: v.optional(v.union(v.id("_storage"), v.null())),
    heroExternalUrl: v.optional(v.string()),
    matchTerms: v.array(v.string()),
    bestTime: v.string(),
    tips: v.array(v.string()),
    costEstimate: v.string(),
    bullets: v.array(v.string()),
    sortOrder: v.optional(v.number()),
  },
  handler: async (ctx, { sessionToken, ...args }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const now = Date.now();
    const base = (args.slug?.trim() || slugifyLocation(args.name)).toLowerCase();
    const slug = await ensureUniqueSlug(ctx, base);
    return await ctx.db.insert("destinations", {
      slug,
      name: args.name.trim(),
      line: args.line.trim(),
      description: args.description.trim(),
      heroStorageId: args.heroStorageId ?? undefined,
      heroExternalUrl: args.heroStorageId
        ? undefined
        : args.heroExternalUrl?.trim() || undefined,
      matchTerms: args.matchTerms.map((t) => t.trim().toLowerCase()).filter(Boolean),
      bestTime: args.bestTime.trim(),
      tips: args.tips.map((t) => t.trim()).filter(Boolean),
      costEstimate: args.costEstimate.trim(),
      bullets: args.bullets.map((b) => b.trim()).filter(Boolean),
      autoGenerated: false,
      sortOrder: args.sortOrder ?? 100,
      createdAt: now,
      updatedAt: now,
    });
  },
});

export const updateDestination = mutation({
  args: {
    sessionToken: v.string(),
    destinationId: v.id("destinations"),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    line: v.optional(v.string()),
    description: v.optional(v.string()),
    /** `null` removes the hero entirely (uploaded AND external image). */
    heroStorageId: v.optional(v.union(v.id("_storage"), v.null())),
    /** `null` clears the external hero URL. */
    heroExternalUrl: v.optional(v.union(v.string(), v.null())),
    matchTerms: v.optional(v.array(v.string())),
    bestTime: v.optional(v.string()),
    tips: v.optional(v.array(v.string())),
    costEstimate: v.optional(v.string()),
    bullets: v.optional(v.array(v.string())),
    sortOrder: v.optional(v.number()),
  },
  handler: async (ctx, { sessionToken, destinationId, ...patch }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const existing = await ctx.db.get(destinationId);
    if (!existing) throw new Error("Destination not found");

    const next: Record<string, unknown> = {};
    for (const [k, val] of Object.entries(patch)) {
      // `undefined` = leave unchanged; `null` = clear.
      if (val !== undefined) next[k] = val === null ? undefined : val;
    }

    if (typeof next.slug === "string") {
      const normalized = String(next.slug).trim().toLowerCase();
      if (!normalized) {
        // A blank slug means "leave it", never "erase the page URL".
        delete next.slug;
      } else {
        if (normalized !== existing.slug) {
          const conflicts = await ctx.db
            .query("destinations")
            .withIndex("by_slug", (q) => q.eq("slug", normalized))
            .take(2);
          if (conflicts.some((c) => c._id !== destinationId)) {
            throw new Error("Slug already exists");
          }
        }
        next.slug = normalized;
      }
    }
    if (typeof next.heroExternalUrl === "string") {
      next.heroExternalUrl = next.heroExternalUrl.trim() || undefined;
    }

    if (Array.isArray(next.matchTerms)) {
      next.matchTerms = (next.matchTerms as string[])
        .map((t) => t.trim().toLowerCase())
        .filter(Boolean);
    }
    if (Array.isArray(next.tips)) {
      next.tips = (next.tips as string[]).map((t) => t.trim()).filter(Boolean);
    }
    if (Array.isArray(next.bullets)) {
      next.bullets = (next.bullets as string[]).map((b) => b.trim()).filter(Boolean);
    }

    // Hero image: `null` removes the hero (both the upload and any external URL,
    // otherwise "Remove" silently kept showing the old image); a new storage id
    // supersedes any legacy URL.
    if (patch.heroStorageId !== undefined) {
      next.heroStorageId = patch.heroStorageId ?? undefined;
      if (patch.heroExternalUrl === undefined || patch.heroStorageId !== null) {
        next.heroExternalUrl = undefined;
      }
    }

    // An admin edit makes the destination admin-owned: AI enrichment and tour
    // hero sync must no longer overwrite it.
    next.autoGenerated = false;
    next.updatedAt = Date.now();

    await ctx.db.patch(
      destinationId,
      next as Partial<Omit<Doc<"destinations">, "_id" | "_creationTime">>,
    );
  },
});

export const deleteDestination = mutation({
  args: { sessionToken: v.string(), destinationId: v.id("destinations") },
  handler: async (ctx, { sessionToken, destinationId }) => {
    await requireAdminFromSession(ctx, sessionToken);
    const tours = await ctx.db.query("tours").collect();
    for (const t of tours) {
      const nextDestinationIds = Array.isArray(t.destinationIds)
        ? t.destinationIds.filter((id) => id !== destinationId)
        : undefined;
      const patch: Record<string, unknown> = {};
      if (t.destinationId === destinationId) {
        patch.destinationId = undefined;
      }
      if (Array.isArray(t.destinationIds) && t.destinationIds.includes(destinationId)) {
        patch.destinationIds = nextDestinationIds;
      }
      if (Object.keys(patch).length > 0) {
        // Bump the revision so an open tour editor re-syncs instead of saving
        // the deleted destination back onto the tour.
        patch.updatedAt = Math.max(Date.now(), (t.updatedAt ?? t.createdAt) + 1);
        await ctx.db.patch(t._id, patch as Partial<Doc<"tours">>);
      }
    }
    await ctx.db.delete(destinationId);
  },
});

/** Fills a destination's hero from a tour image ONLY when it has no hero at all. */
async function fillMissingHero(
  ctx: MutationCtx,
  destination: Doc<"destinations">,
  primary: ReturnType<typeof primaryVisualFromImages>,
) {
  if (destination.heroStorageId || destination.heroExternalUrl) return;
  if (!primary.heroStorageId && !primary.heroExternalUrl) return;
  await ctx.db.patch(destination._id, { ...primary });
}

export const syncFromTour = internalMutation({
  args: {
    tourId: v.id("tours"),
    /**
     * Only tour CREATION may auto-create a destination. Updates just fill
     * missing heroes, so a destination an admin deleted is never resurrected.
     */
    allowCreate: v.optional(v.boolean()),
  },
  handler: async (ctx, { tourId, allowCreate }) => {
    const tour = await ctx.db.get(tourId);
    if (!tour || !tour.isActive) return;

    const dests = await ctx.db.query("destinations").collect();
    const primary = primaryVisualFromImages(tour.images);
    const now = Date.now();
    const assignedDestinationIds = [
      ...(Array.isArray(tour.destinationIds) ? tour.destinationIds : []),
      ...(tour.destinationId ? [tour.destinationId] : []),
    ];

    if (assignedDestinationIds.length > 0) {
      const uniqueAssigned = Array.from(new Set(assignedDestinationIds));
      for (const destinationId of uniqueAssigned) {
        const assigned = await ctx.db.get(destinationId);
        if (!assigned) continue;
        await fillMissingHero(ctx, assigned, primary);
      }
      return;
    }

    const matched = dests.filter((d) =>
      locationMatchesTerms(tour.location, d.matchTerms),
    );

    if (matched.length > 0) {
      for (const d of matched) {
        await fillMissingHero(ctx, d, primary);
      }
      return;
    }

    if (!allowCreate) return;

    // Don't create "skardu-1" when a "Skardu" destination already exists but
    // its match terms simply don't cover this tour's location text.
    const base = slugifyLocation(tour.location);
    const wantedName = readableName(tour.location).toLowerCase();
    const sameRegion = dests.find(
      (d) => d.slug === base || d.name.trim().toLowerCase() === wantedName,
    );
    if (sameRegion) {
      await fillMissingHero(ctx, sameRegion, primary);
      return;
    }

    const slug = await ensureUniqueSlug(ctx, base);
    const newDestinationId = await ctx.db.insert("destinations", {
      slug,
      name: readableName(tour.location),
      line: "Tours and experiences in this region.",
      description: `Browse active tours and packages covering ${tour.location}.`,
      matchTerms: matchTermsFromLocation(tour.location, slug),
      bestTime:
        "Contact us for the best seasonal windows and road status for this area.",
      tips: [
        "Book transport and stays early in peak season.",
        "Confirm road and pass status before travel.",
      ],
      costEstimate:
        "Pricing varies by group size and inclusions — see individual tours in this region.",
      bullets: [
        "Hand-picked routes from our catalog.",
        "Combine with nearby regions for longer trips.",
      ],
      autoGenerated: true,
      sortOrder: 1000,
      createdAt: now,
      updatedAt: now,
      ...primary,
    });

    // Replace the generic placeholder content with AI-generated guide copy and
    // link the correct province — runs async so tour creation stays instant.
    await ctx.scheduler.runAfter(0, internal.ai.enrichAutoDestination, {
      destinationId: newDestinationId,
      tourId,
    });
  },
});

/** Context for AI enrichment of an auto-generated destination (see convex/ai.ts). */
export const getAutoEnrichContext = internalQuery({
  args: { destinationId: v.id("destinations"), tourId: v.id("tours") },
  handler: async (ctx, { destinationId, tourId }) => {
    const destination = await ctx.db.get(destinationId);
    const tour = await ctx.db.get(tourId);
    if (!destination || !tour) return null;
    const provinces = await ctx.db.query("provinces").collect();
    return {
      destination: {
        slug: destination.slug,
        name: destination.name,
        autoGenerated: destination.autoGenerated,
      },
      tour: {
        title: tour.title,
        location: tour.location,
        description: tour.description.slice(0, 1500),
        days: tour.itinerary.map((d) => d.title).slice(0, 20),
        hasProvince: Array.isArray(tour.provinceIds) && tour.provinceIds.length > 0,
      },
      provinces: provinces.map((p) => ({ slug: p.slug, name: p.name })),
    };
  },
});

/**
 * Finds an existing, curated (non-auto-generated) province by slug.
 *
 * AI enrichment used to CREATE provinces for any slug the model invented, which
 * polluted /guides with placeholder regions. Linking is now lookup-only.
 */
async function findCuratedProvince(
  ctx: MutationCtx,
  slug: string,
): Promise<Doc<"provinces"> | null> {
  const normalizedSlug = slug.trim().toLowerCase();
  if (!normalizedSlug) return null;
  const existing = await ctx.db
    .query("provinces")
    .withIndex("by_slug", (q) => q.eq("slug", normalizedSlug))
    .first();
  if (!existing || existing.autoGenerated) return null;
  return existing;
}

/**
 * Applies AI-generated content onto a still-untouched auto-generated
 * destination and links an EXISTING curated province. Never creates provinces
 * and never replaces a tour's province assignment.
 */
export const applyAutoEnrichment = internalMutation({
  args: {
    destinationId: v.id("destinations"),
    tourId: v.id("tours"),
    name: v.optional(v.string()),
    line: v.optional(v.string()),
    description: v.optional(v.string()),
    bestTime: v.optional(v.string()),
    costEstimate: v.optional(v.string()),
    tips: v.optional(v.array(v.string())),
    bullets: v.optional(v.array(v.string())),
    matchTerms: v.optional(v.array(v.string())),
    provinceSlug: v.optional(v.string()),
    provinceName: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const dest = await ctx.db.get(args.destinationId);
    if (!dest) return;
    // Never overwrite admin-authored destinations, or auto ones an admin has
    // already edited/imported over (the AI call can finish long after creation).
    if (!dest.autoGenerated) return;
    if (dest.updatedAt !== dest.createdAt) return;

    const patch: Record<string, unknown> = {};
    if (args.name?.trim()) patch.name = args.name.trim().slice(0, 80);
    if (args.line?.trim()) patch.line = args.line.trim();
    if (args.description?.trim()) patch.description = args.description.trim();
    if (args.bestTime?.trim()) patch.bestTime = args.bestTime.trim();
    if (args.costEstimate?.trim()) patch.costEstimate = args.costEstimate.trim();
    if (args.tips && args.tips.length) patch.tips = args.tips.slice(0, 6);
    if (args.bullets && args.bullets.length) patch.bullets = args.bullets.slice(0, 6);
    if (args.matchTerms && args.matchTerms.length) {
      patch.matchTerms = Array.from(
        new Set([
          ...(dest.matchTerms ?? []),
          ...args.matchTerms.map((t) => t.trim().toLowerCase()).filter(Boolean),
        ]),
      );
    }

    if (args.provinceSlug?.trim()) {
      const province = await findCuratedProvince(ctx, args.provinceSlug);
      if (province) {
        if (!dest.provinceSlug) patch.provinceSlug = province.slug;
        const tour = await ctx.db.get(args.tourId);
        // Only fill an empty assignment; never replace what an admin picked.
        if (tour && !(Array.isArray(tour.provinceIds) && tour.provinceIds.length > 0)) {
          await ctx.db.patch(tour._id, { provinceIds: [province._id] });
        }
      }
    }

    // No `updatedAt` bump: keeps `updatedAt === createdAt` so the untouched
    // check above stays meaningful (enrichment is a system write).
    await ctx.db.patch(args.destinationId, patch);
  },
});

export const listForIndex = query({
  args: {},
  handler: async (ctx) => {
    const dests = await ctx.db.query("destinations").collect();
    if (dests.length === 0) return [];
    const active = await ctx.db
      .query("tours")
      .withIndex("by_isActive", (q) => q.eq("isActive", true))
      .take(500);
    const sorted = dests.sort(
      (a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name),
    );
    return Promise.all(
      sorted.map(async (d) => {
        const matched = active.filter((t) =>
          belongsToDestination(t, d),
        );
        const heroUrl = await resolveDestinationHeroUrl(ctx, d);
        const preview = await Promise.all(
          matched.slice(0, 3).map(async (t) => ({
            slug: t.slug,
            title: t.title,
            price: t.price,
            pricePkr: t.pricePkr,
            priceUsd: t.priceUsd,
            perHeadPrices: t.perHeadPrices ?? [],
            images: await resolveTourImageUrls(ctx, t.images),
          })),
        );
        return {
          slug: d.slug,
          name: d.name,
          line: d.line,
          heroUrl,
          tourCount: matched.length,
          previewTours: preview,
          moreCount: Math.max(0, matched.length - 3),
        };
      }),
    );
  },
});

export const getPublicBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const d = await findDestinationBySlug(ctx, slug);
    if (!d) return null;
    const heroUrl = await resolveDestinationHeroUrl(ctx, d);
    return {
      slug: d.slug,
      name: d.name,
      line: d.line,
      description: d.description,
      heroUrl,
      bestTime: d.bestTime,
      tips: d.tips,
      costEstimate: d.costEstimate,
      bullets: d.bullets,
      matchTerms: d.matchTerms,
    };
  },
});

export const listSlugs = query({
  args: {},
  handler: async (ctx) => {
    const dests = await ctx.db.query("destinations").collect();
    return dests.map((d) => d.slug);
  },
});

export const listRelatedTours = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const d = await findDestinationBySlug(ctx, slug);
    if (!d) return [];
    const tours = await ctx.db.query("tours").collect();
    const matched = tours.filter(
      (t) =>
        t.isActive && belongsToDestination(t, d),
    );
    return Promise.all(
      matched.slice(0, 12).map(async (t) => ({
        slug: t.slug,
        title: t.title,
        description: t.description,
        price: t.price,
        pricePkr: t.pricePkr,
        priceUsd: t.priceUsd,
        perHeadPrices: t.perHeadPrices ?? [],
        durationDays: t.durationDays,
        location: t.location,
        images: await resolveTourImageUrls(ctx, t.images),
      })),
    );
  },
});

export const bulkUpsert = mutation({
  args: {
    sessionToken: v.string(),
    rows: v.array(
      v.object({
        slug: v.optional(v.string()),
        name: v.string(),
        line: v.string(),
        description: v.string(),
        heroExternalUrl: v.optional(v.string()),
        matchTerms: v.array(v.string()),
        bestTime: v.string(),
        tips: v.array(v.string()),
        costEstimate: v.string(),
        bullets: v.array(v.string()),
        sortOrder: v.optional(v.number()),
      }),
    ),
  },
  handler: async (ctx, { sessionToken, rows }) => {
    const admin = await requireAdminFromSession(ctx, sessionToken);
    const now = Date.now();
    let created = 0;
    let updated = 0;
    let skipped = 0;
    const errors: Array<{ index: number; message: string }> = [];

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i]!;
      try {
        const base = (row.slug?.trim() || slugifyLocation(row.name)).toLowerCase();
        if (!row.name.trim()) throw new Error("name is required");
        if (!row.line.trim()) throw new Error("line is required");
        if (!row.description.trim()) throw new Error("description is required");
        if (!row.bestTime.trim()) throw new Error("bestTime is required");
        if (!row.costEstimate.trim()) throw new Error("costEstimate is required");

        const normalizedSlug = base;
        const existing = await findDestinationBySlug(ctx, normalizedSlug);

        const name = row.name.trim();
        const line = row.line.trim();
        const description = row.description.trim();
        const bestTime = row.bestTime.trim();
        const costEstimate = row.costEstimate.trim();
        const heroExternalUrl = row.heroExternalUrl?.trim() || undefined;
        const matchTerms = row.matchTerms.map((t) => t.trim().toLowerCase()).filter(Boolean);
        const tips = row.tips.map((t) => t.trim()).filter(Boolean);
        const bullets = row.bullets.map((b) => b.trim()).filter(Boolean);

        if (existing) {
          // UPDATE: only write columns that were actually filled in. Blank
          // lists, a blank hero URL or a missing sortOrder keep what's there.
          const patch: Partial<Doc<"destinations">> = {
            name,
            line,
            description,
            bestTime,
            costEstimate,
            // An admin import owns the row from now on.
            autoGenerated: false,
            updatedAt: now + i,
          };
          if (heroExternalUrl) patch.heroExternalUrl = heroExternalUrl;
          if (matchTerms.length > 0) patch.matchTerms = matchTerms;
          if (tips.length > 0) patch.tips = tips;
          if (bullets.length > 0) patch.bullets = bullets;
          if (row.sortOrder !== undefined) patch.sortOrder = row.sortOrder;
          await ctx.db.patch(existing._id, patch);
          updated++;
        } else {
          const slug = await ensureUniqueSlug(ctx, normalizedSlug);
          await ctx.db.insert("destinations", {
            slug,
            name,
            line,
            description,
            heroExternalUrl,
            matchTerms,
            bestTime,
            tips,
            costEstimate,
            bullets,
            sortOrder: row.sortOrder ?? 100,
            autoGenerated: false,
            createdAt: now + i,
            updatedAt: now + i,
          });
          created++;
        }
      } catch (e) {
        errors.push({ index: i, message: e instanceof Error ? e.message : String(e) });
        skipped++;
      }
    }

    await ctx.db.insert("adminLogs", {
      action: "bulk_upsert_destinations",
      performedBy: admin._id,
      timestamp: Date.now(),
      details: `processed=${rows.length} created=${created} updated=${updated} skipped=${skipped}`,
    });

    return { processed: rows.length, created, updated, skipped, errors };
  },
});
