import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    phone: v.optional(v.string()),
    phoneNormalized: v.optional(v.string()),
    passwordHash: v.string(),
    role: v.union(
      v.literal("super_admin"),
      v.literal("admin"),
      v.literal("customer"),
    ),
    emailVerified: v.optional(v.boolean()),
    createdAt: v.number(),
  })
    .index("by_email", ["email"])
    .index("by_phone_normalized", ["phoneNormalized"]),

  sessions: defineTable({
    userId: v.id("users"),
    tokenHash: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_token_hash", ["tokenHash"])
    .index("by_user", ["userId"]),

  guestBookings: defineTable({
    name: v.string(),
    phone: v.string(),
    phoneNormalized: v.string(),
    email: v.optional(v.string()),
    tourId: v.id("tours"),
    peopleCount: v.number(),
    notes: v.optional(v.string()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    departureCity: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    specialNeeds: v.optional(v.string()),
    status: v.union(
      v.literal("pending"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    linkedUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_phone_normalized", ["phoneNormalized"])
    .index("by_email", ["email"])
    .index("by_tour", ["tourId"])
    .index("by_linked_user", ["linkedUserId"]),

  bookings: defineTable({
    userId: v.id("users"),
    tourId: v.id("tours"),
    peopleCount: v.number(),
    totalPrice: v.number(),
    status: v.union(
      v.literal("pending"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    notes: v.optional(v.string()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    departureCity: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    specialNeeds: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_tour", ["tourId"]),

  tours: defineTable({
    title: v.string(),
    slug: v.string(),
    description: v.string(),
    /** Business-defined tour categories used by homepage/type filtering. */
    types: v.optional(v.array(v.string())),
    /** Optional explicit destination assignments for admin-managed grouping. */
    destinationIds: v.optional(v.array(v.id("destinations"))),
    /** Legacy single destination fallback kept for existing records. */
    destinationId: v.optional(v.id("destinations")),
    price: v.number(),
    durationDays: v.number(),
    location: v.string(),
    office: v.optional(v.string()),
    email: v.optional(v.string()),
    /** Convex `_storage` ids and/or `https?://` or `/` paths (resolved at read time). */
    images: v.array(v.string()),
    /** Logical folder for uploads: `tours/{slug}` (mirrored in `tourImageAssets`). */
    imageFolderKey: v.optional(v.string()),
    itinerary: v.array(
      v.object({
        day: v.number(),
        title: v.string(),
        description: v.string(),
      }),
    ),
    isActive: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  /** Indexes Convex `_storage` ids under a logical folder per tour (see `imageFolderKey`). */
  tourImageAssets: defineTable({
    tourId: v.id("tours"),
    folderKey: v.string(),
    storageId: v.id("_storage"),
    createdAt: v.number(),
  })
    .index("by_tour", ["tourId"])
    .index("by_folder", ["folderKey"])
    .index("by_storage", ["storageId"]),

  /** Indexes Convex `_storage` ids under a logical folder per itinerary (wizard image picker). */
  itineraryImageAssets: defineTable({
    itineraryId: v.id("itineraries"),
    folderKey: v.string(),
    storageId: v.id("_storage"),
    createdAt: v.number(),
  })
    .index("by_itinerary", ["itineraryId"])
    .index("by_folder", ["folderKey"])
    .index("by_storage", ["storageId"]),

  /** Regions for /destinations — seeded + auto-created when tours use new locations. */
  destinations: defineTable({
    slug: v.string(),
    name: v.string(),
    line: v.string(),
    description: v.string(),
    heroStorageId: v.optional(v.id("_storage")),
    heroExternalUrl: v.optional(v.string()),
    matchTerms: v.array(v.string()),
    bestTime: v.string(),
    tips: v.array(v.string()),
    costEstimate: v.string(),
    bullets: v.array(v.string()),
    autoGenerated: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  /** Optional: site-wide assets (logo, etc.) stored in Convex — keyed for lookup. */
  siteAssets: defineTable({
    key: v.string(),
    storageId: v.id("_storage"),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),

  siteSettings: defineTable({
    key: v.string(),
    officeAddress: v.optional(v.string()),
    whatsappPhone: v.optional(v.string()),
    contactEmail: v.optional(v.string()),
    website: v.optional(v.string()),
    governmentLicenseNo: v.optional(v.string()),
    mapsEmbedUrl: v.optional(v.string()),
    /** Global itinerary PDF boilerplate (same on every proposal). */
    paymentTerms: v.optional(
      v.array(
        v.object({
          percent: v.number(),
          title: v.string(),
          description: v.optional(v.string()),
        }),
      ),
    ),
    bankDetails: v.optional(
      v.object({
        bankName: v.optional(v.string()),
        accountTitle: v.optional(v.string()),
        accountNumber: v.optional(v.string()),
        iban: v.optional(v.string()),
        instruction: v.optional(v.string()),
      }),
    ),
    termsBlocks: v.optional(
      v.array(
        v.object({
          title: v.string(),
          body: v.string(),
        }),
      ),
    ),
    defaultIncluded: v.optional(v.array(v.string())),
    defaultNotIncluded: v.optional(v.array(v.string())),
    updatedAt: v.number(),
    updatedBy: v.optional(v.id("users")),
  }).index("by_key", ["key"]),

  leads: defineTable({
    name: v.string(),
    phone: v.string(),
    source: v.union(
      v.literal("AI"),
      v.literal("Booking"),
      v.literal("Manual"),
    ),
    message: v.optional(v.string()),
    createdAt: v.number(),
  }),

  aiRequests: defineTable({
    userId: v.optional(v.id("users")),
    input: v.string(),
    output: v.string(),
    type: v.string(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  /** Anonymous + optional logged-in planner widget / chat persistence (guestSessionId from browser). */
  plannerChatSessions: defineTable({
    guestSessionId: v.string(),
    userId: v.optional(v.id("users")),
    messages: v.array(
      v.object({
        role: v.union(v.literal("user"), v.literal("assistant")),
        content: v.string(),
      }),
    ),
    planSnapshot: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_guest_session", ["guestSessionId"]),

  blogPosts: defineTable({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
    published: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  adminLogs: defineTable({
    action: v.string(),
    performedBy: v.id("users"),
    targetUser: v.optional(v.id("users")),
    timestamp: v.number(),
    details: v.optional(v.string()),
  }).index("by_timestamp", ["timestamp"]),

  /** AI-suggested custom itineraries awaiting admin review */
  customItineraryRequests: defineTable({
    userId: v.optional(v.id("users")),
    name: v.string(),
    phone: v.string(),
    email: v.optional(v.string()),
    summary: v.string(),
    proposal: v.string(),
    /** Full AI planner chat thread (latest window). */
    thread: v.optional(
      v.array(
        v.object({
          role: v.union(v.literal("user"), v.literal("assistant")),
          content: v.string(),
        }),
      ),
    ),
    /** Ops workspace: admin-drafted itinerary/quote text. */
    adminDraft: v.optional(v.string()),
    adminDraftUpdatedAt: v.optional(v.number()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
    ),
    adminNote: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    reviewedBy: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),

  itineraries: defineTable({
    /** Cover headline, e.g. "Your Dream Skardu Awaits —" */
    headline: v.optional(v.string()),
    /** Cover variant label, e.g. "Customised by Air" */
    variantLabel: v.optional(v.string()),
    /** Cover subtitle line (optional marketing line) */
    coverSubtitle: v.optional(v.string()),
    /** Compliance/registration line shown under subtitle */
    complianceLine: v.optional(v.string()),
    /** License number shown in footer/header */
    licenceNumber: v.optional(v.string()),
    /** Pickup/dropoff line shown on cover */
    pickupDropoff: v.optional(v.string()),

    title: v.string(),
    clientName: v.string(),
    startDate: v.string(),
    endDate: v.string(),
    days: v.number(),
    theme: v.union(
      v.literal("luxury"),
      v.literal("minimal"),
      v.literal("adventure"),
    ),
    status: v.union(v.literal("draft"), v.literal("final")),

    coverImageStorageId: v.optional(v.id("_storage")),

    companyDescription: v.optional(v.string()),
    logoStorageId: v.optional(v.id("_storage")),
    affiliationsStorageIds: v.optional(v.array(v.id("_storage"))),
    contactPhone: v.optional(v.string()),
    contactEmail: v.optional(v.string()),
    contactWebsite: v.optional(v.string()),

    destinations: v.optional(v.array(v.string())),
    /** Optional linkage to a rate-card record (legacy string id). */
    rateCardId: v.optional(v.string()),
    /** Optional linkage to an itinerary template (legacy string id). */
    templateId: v.optional(v.string()),
    transportType: v.optional(v.string()),
    accommodationType: v.optional(v.string()),
    mealsIncluded: v.optional(v.string()),

    dayPlans: v.optional(
      v.array(
        v.object({
          dayNumber: v.number(),
          title: v.string(),
          imageStorageId: v.optional(v.id("_storage")),
          /** Quick PDF-style highlights list (used in proposal template). */
          highlights: v.optional(v.array(v.string())),
          /** Overnight city/location (used in proposal template). */
          overnight: v.optional(v.string()),
          morning: v.array(
            v.object({
              title: v.string(),
              description: v.string(),
              icon: v.union(
                v.literal("flight"),
                v.literal("hotel"),
                v.literal("food"),
                v.literal("sightseeing"),
              ),
            }),
          ),
          afternoon: v.array(
            v.object({
              title: v.string(),
              description: v.string(),
              icon: v.union(
                v.literal("flight"),
                v.literal("hotel"),
                v.literal("food"),
                v.literal("sightseeing"),
              ),
            }),
          ),
          evening: v.array(
            v.object({
              title: v.string(),
              description: v.string(),
              icon: v.union(
                v.literal("flight"),
                v.literal("hotel"),
                v.literal("food"),
                v.literal("sightseeing"),
              ),
            }),
          ),
        }),
      ),
    ),

    accommodationDetails: v.optional(v.string()),
    included: v.optional(v.array(v.string())),
    notIncluded: v.optional(v.array(v.string())),
    importantNotes: v.optional(v.string()),

    /** Proposal packages displayed in "Choose Your Package" section. */
    packages: v.optional(
      v.array(
        v.object({
          name: v.string(),
          pricePkr: v.optional(v.number()),
          vehicle: v.optional(v.string()),
          note: v.optional(v.string()),
          stays: v.optional(
            v.array(
              v.object({
                location: v.string(),
                hotel: v.string(),
                nights: v.number(),
              }),
            ),
          ),
        }),
      ),
    ),
    /** Payment terms shown as percentage blocks. */
    paymentTerms: v.optional(
      v.array(
        v.object({
          percent: v.number(),
          title: v.string(),
          description: v.optional(v.string()),
        }),
      ),
    ),
    bankDetails: v.optional(
      v.object({
        bankName: v.optional(v.string()),
        accountTitle: v.optional(v.string()),
        accountNumber: v.optional(v.string()),
        iban: v.optional(v.string()),
        instruction: v.optional(v.string()),
      }),
    ),
    termsBlocks: v.optional(
      v.array(
        v.object({
          title: v.string(),
          body: v.string(),
        }),
      ),
    ),

    /** "simple" = new canvas builder + template constants from site settings; "advanced" = legacy wizard. */
    layoutVariant: v.optional(
      v.union(v.literal("simple"), v.literal("advanced")),
    ),
    /** Straight-down itinerary at a glance (simple layout). */
    atGlanceDays: v.optional(
      v.array(
        v.object({
          dayNumber: v.number(),
          title: v.string(),
          detail: v.string(),
          overnight: v.optional(v.string()),
        }),
      ),
    ),
    /** Shared stay rows (locations) for package matrix in simple layout. */
    packageStayRows: v.optional(
      v.array(
        v.object({
          location: v.string(),
        }),
      ),
    ),
    /** Package tiers; hotels array aligns by index with packageStayRows. */
    packageTiers: v.optional(
      v.array(
        v.object({
          name: v.string(),
          pricePkr: v.optional(v.number()),
          vehicle: v.optional(v.string()),
          note: v.optional(v.string()),
          hotels: v.array(
            v.object({
              hotel: v.string(),
              nights: v.number(),
            }),
          ),
        }),
      ),
    ),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),

  invoices: defineTable({
    /** Unique invoice number label, e.g. "INV/26-27/0001" */
    invoiceNumber: v.optional(v.string()),
    clientName: v.string(),
    itineraryId: v.optional(v.id("itineraries")),
    invoiceDate: v.string(),
    currency: v.union(v.literal("PKR"), v.literal("USD")),
    status: v.union(v.literal("draft"), v.literal("paid")),

    items: v.array(
      v.object({
        name: v.string(),
        description: v.optional(v.string()),
        quantity: v.number(),
        price: v.number(),
      }),
    ),
    discount: v.number(),
    tax: v.number(),
    /** Amount already received from the client */
    advanceAmount: v.optional(v.number()),
    /** Admin-entered summary of the trip (shown on invoice) */
    tripSummary: v.optional(v.string()),

    paymentMethod: v.union(
      v.literal("bank"),
      v.literal("easypaisa"),
      v.literal("jazzcash"),
    ),
    paymentDetails: v.string(),

    terms: v.optional(v.string()),
    cancellationPolicy: v.optional(v.string()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_itinerary", ["itineraryId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),

  invoiceCounters: defineTable({
    /** Fiscal-year key, e.g. "26-27" */
    fiscalYearKey: v.string(),
    /** Next sequence number to issue (starts at 1) */
    nextSeq: v.number(),
    updatedAt: v.number(),
  }).index("by_fiscal_year", ["fiscalYearKey"]),
});
