import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    phone: v.optional(v.string()),
    phoneNormalized: v.optional(v.string()),
    passwordHash: v.string(),
    role: v.union(
      v.literal("super_admin"),
      v.literal("admin"),
      v.literal("customer"),
    ),
    emailVerified: v.optional(v.boolean()),
    createdAt: v.number(),
  })
    .index("by_email", ["email"])
    .index("by_phone_normalized", ["phoneNormalized"]),

  sessions: defineTable({
    userId: v.id("users"),
    tokenHash: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_token_hash", ["tokenHash"])
    .index("by_user", ["userId"]),

  guestBookings: defineTable({
    name: v.string(),
    phone: v.string(),
    phoneNormalized: v.string(),
    email: v.optional(v.string()),
    tourId: v.id("tours"),
    peopleCount: v.number(),
    notes: v.optional(v.string()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    departureCity: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    specialNeeds: v.optional(v.string()),
    status: v.union(
      v.literal("pending"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    linkedUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_phone_normalized", ["phoneNormalized"])
    .index("by_email", ["email"])
    .index("by_tour", ["tourId"])
    .index("by_linked_user", ["linkedUserId"]),

  bookings: defineTable({
    userId: v.id("users"),
    tourId: v.id("tours"),
    peopleCount: v.number(),
    totalPrice: v.number(),
    status: v.union(
      v.literal("pending"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    notes: v.optional(v.string()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    departureCity: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    specialNeeds: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_tour", ["tourId"]),

  tours: defineTable({
    title: v.string(),
    slug: v.string(),
    description: v.string(),
    /** Business-defined tour categories used by homepage/type filtering. */
    types: v.optional(v.array(v.string())),
    /** Optional explicit destination assignments for admin-managed grouping. */
    destinationIds: v.optional(v.array(v.id("destinations"))),
    /** Legacy single destination fallback kept for existing records. */
    destinationId: v.optional(v.id("destinations")),
    price: v.number(),
    durationDays: v.number(),
    location: v.string(),
    office: v.optional(v.string()),
    email: v.optional(v.string()),
    /** Convex `_storage` ids and/or `https?://` or `/` paths (resolved at read time). */
    images: v.array(v.string()),
    /** Logical folder for uploads: `tours/{slug}` (mirrored in `tourImageAssets`). */
    imageFolderKey: v.optional(v.string()),
    itinerary: v.array(
      v.object({
        day: v.number(),
        title: v.string(),
        description: v.string(),
      }),
    ),
    isActive: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  /** Indexes Convex `_storage` ids under a logical folder per tour (see `imageFolderKey`). */
  tourImageAssets: defineTable({
    tourId: v.id("tours"),
    folderKey: v.string(),
    storageId: v.id("_storage"),
    createdAt: v.number(),
  })
    .index("by_tour", ["tourId"])
    .index("by_folder", ["folderKey"])
    .index("by_storage", ["storageId"]),

  /** Regions for /destinations — seeded + auto-created when tours use new locations. */
  destinations: defineTable({
    slug: v.string(),
    name: v.string(),
    line: v.string(),
    description: v.string(),
    heroStorageId: v.optional(v.id("_storage")),
    heroExternalUrl: v.optional(v.string()),
    matchTerms: v.array(v.string()),
    bestTime: v.string(),
    tips: v.array(v.string()),
    costEstimate: v.string(),
    bullets: v.array(v.string()),
    autoGenerated: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  /** Optional: site-wide assets (logo, etc.) stored in Convex — keyed for lookup. */
  siteAssets: defineTable({
    key: v.string(),
    storageId: v.id("_storage"),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),

  siteSettings: defineTable({
    key: v.string(),
    officeAddress: v.optional(v.string()),
    whatsappPhone: v.optional(v.string()),
    contactEmail: v.optional(v.string()),
    mapsEmbedUrl: v.optional(v.string()),
    updatedAt: v.number(),
    updatedBy: v.optional(v.id("users")),
  }).index("by_key", ["key"]),

  leads: defineTable({
    name: v.string(),
    phone: v.string(),
    source: v.union(
      v.literal("AI"),
      v.literal("Booking"),
      v.literal("Manual"),
    ),
    message: v.optional(v.string()),
    createdAt: v.number(),
  }),

  aiRequests: defineTable({
    userId: v.optional(v.id("users")),
    input: v.string(),
    output: v.string(),
    type: v.string(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  /** Anonymous + optional logged-in planner widget / chat persistence (guestSessionId from browser). */
  plannerChatSessions: defineTable({
    guestSessionId: v.string(),
    userId: v.optional(v.id("users")),
    messages: v.array(
      v.object({
        role: v.union(v.literal("user"), v.literal("assistant")),
        content: v.string(),
      }),
    ),
    planSnapshot: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_guest_session", ["guestSessionId"]),

  blogPosts: defineTable({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
    published: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  adminLogs: defineTable({
    action: v.string(),
    performedBy: v.id("users"),
    targetUser: v.optional(v.id("users")),
    timestamp: v.number(),
    details: v.optional(v.string()),
  }).index("by_timestamp", ["timestamp"]),

  /** AI-suggested custom itineraries awaiting admin review */
  customItineraryRequests: defineTable({
    userId: v.optional(v.id("users")),
    name: v.string(),
    phone: v.string(),
    email: v.optional(v.string()),
    summary: v.string(),
    proposal: v.string(),
    /** Full AI planner chat thread (latest window). */
    thread: v.optional(
      v.array(
        v.object({
          role: v.union(v.literal("user"), v.literal("assistant")),
          content: v.string(),
        }),
      ),
    ),
    /** Ops workspace: admin-drafted itinerary/quote text. */
    adminDraft: v.optional(v.string()),
    adminDraftUpdatedAt: v.optional(v.number()),
    preferredStart: v.optional(v.string()),
    preferredEnd: v.optional(v.string()),
    adults: v.optional(v.number()),
    children: v.optional(v.number()),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
    ),
    adminNote: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    reviewedBy: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),
});
