"use client";

import { useMutation, useQuery } from "convex/react";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { toUserFacingErrorMessage } from "@/lib/userFriendlyError";

type DestinationRow = {
  _id: Id<"destinations">;
  slug: string;
  name: string;
  line: string;
  description: string;
  heroExternalUrl?: string;
  matchTerms: string[];
  bestTime: string;
  tips: string[];
  costEstimate: string;
  bullets: string[];
  sortOrder: number;
  autoGenerated: boolean;
  tourCount: number;
};

function toLines(v: string[]): string {
  return v.join("\n");
}

function fromLines(v: string): string[] {
  return v
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

export function AdminDestinationsPanel() {
  const rows = useQuery(api.destinations.listForAdmin, {});
  const seedDestinations = useMutation(api.destinations.seedDefaults);
  const createDestination = useMutation(api.destinations.createDestination);
  const updateDestination = useMutation(api.destinations.updateDestination);
  const deleteDestination = useMutation(api.destinations.deleteDestination);

  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<Id<"destinations"> | null>(null);

  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [line, setLine] = useState("");
  const [description, setDescription] = useState("");
  const [heroExternalUrl, setHeroExternalUrl] = useState("");
  const [sortOrder, setSortOrder] = useState(100);
  const [matchTermsInput, setMatchTermsInput] = useState("");
  const [bestTime, setBestTime] = useState("");
  const [tipsInput, setTipsInput] = useState("");
  const [costEstimate, setCostEstimate] = useState("");
  const [bulletsInput, setBulletsInput] = useState("");

  const [msg, setMsg] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const list = useMemo(() => (rows ?? []) as DestinationRow[], [rows]);

  function resetForm() {
    setName("");
    setSlug("");
    setLine("");
    setDescription("");
    setHeroExternalUrl("");
    setSortOrder(100);
    setMatchTermsInput("");
    setBestTime("");
    setTipsInput("");
    setCostEstimate("");
    setBulletsInput("");
  }

  function openNew() {
    setEditingId(null);
    resetForm();
    setMsg(null);
    setModalOpen(true);
  }

  function openEdit(d: DestinationRow) {
    setEditingId(d._id);
    setName(d.name);
    setSlug(d.slug);
    setLine(d.line);
    setDescription(d.description);
    setHeroExternalUrl(d.heroExternalUrl ?? "");
    setSortOrder(d.sortOrder);
    setMatchTermsInput(toLines(d.matchTerms));
    setBestTime(d.bestTime);
    setTipsInput(toLines(d.tips));
    setCostEstimate(d.costEstimate);
    setBulletsInput(toLines(d.bullets));
    setMsg(null);
    setModalOpen(true);
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setMsg(null);

    const payload = {
      name,
      slug: slug.trim() || undefined,
      line,
      description,
      heroExternalUrl: heroExternalUrl.trim() || undefined,
      sortOrder,
      matchTerms: fromLines(matchTermsInput),
      bestTime,
      tips: fromLines(tipsInput),
      costEstimate,
      bullets: fromLines(bulletsInput),
    };

    try {
      if (editingId) {
        await updateDestination({ destinationId: editingId, ...payload });
        setMsg("Destination updated.");
      } else {
        await createDestination(payload);
        setMsg("Destination created.");
      }
      setModalOpen(false);
    } catch (err) {
      setMsg(toUserFacingErrorMessage(err));
    } finally {
      setSaving(false);
    }
  }

  if (rows === undefined) {
    return <p className="text-sm text-brand-muted">Loading…</p>;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Button type="button" variant="primary" onClick={openNew}>
          <Plus className="h-4 w-4" aria-hidden />
          Add destination
        </Button>
        <Button type="button" variant="secondary" onClick={() => void seedDestinations({})}>
          Seed sample destinations
        </Button>
        {msg && !modalOpen ? (
          <span className="text-sm text-brand-muted">{msg}</span>
        ) : null}
      </div>

      <div className="overflow-x-auto rounded-xl border border-slate-200/90 bg-white shadow-sm">
        <table className="min-w-[760px] w-full text-left text-sm">
          <thead className="border-b border-slate-200 bg-slate-50/90 text-xs font-semibold uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-4 py-3">Name</th>
              <th className="px-4 py-3">Slug</th>
              <th className="px-4 py-3">Order</th>
              <th className="px-4 py-3">Tours</th>
              <th className="px-4 py-3">Source</th>
              <th className="px-4 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {list.map((d) => (
              <tr key={d._id} className="border-b border-slate-100 last:border-0">
                <td className="px-4 py-3 font-medium text-brand-ink">{d.name}</td>
                <td className="px-4 py-3 text-slate-600">/{d.slug}</td>
                <td className="px-4 py-3 text-slate-600">{d.sortOrder}</td>
                <td className="px-4 py-3 text-slate-600">{d.tourCount}</td>
                <td className="px-4 py-3">
                  <span
                    className={d.autoGenerated
                      ? "rounded-full bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-900"
                      : "rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-900"}
                  >
                    {d.autoGenerated ? "Auto" : "Manual"}
                  </span>
                </td>
                <td className="px-4 py-3 text-right">
                  <div className="flex flex-wrap justify-end gap-1">
                    <button
                      type="button"
                      className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-brand-primary hover:bg-slate-50"
                      onClick={() => openEdit(d)}
                    >
                      <Pencil className="h-3.5 w-3.5" aria-hidden />
                      Edit
                    </button>
                    <button
                      type="button"
                      className="inline-flex items-center gap-1 text-xs font-semibold text-red-600 hover:underline"
                      onClick={() => {
                        if (confirm("Delete this destination? Tours assigned to it will be unassigned.")) {
                          void deleteDestination({ destinationId: d._id });
                        }
                      }}
                    >
                      <Trash2 className="h-3.5 w-3.5" aria-hidden />
                      Delete
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {list.length === 0 ? (
          <p className="p-6 text-sm text-slate-500">No destinations yet.</p>
        ) : null}
      </div>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editingId ? "Edit destination" : "Add destination"}
        description="Manage destination details and matching terms used by destination pages."
        panelClassName="max-w-2xl"
        fullscreenOnMobile
      >
        <form onSubmit={onSubmit} className="space-y-3">
          {msg && modalOpen ? (
            <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900">
              {msg}
            </p>
          ) : null}

          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block text-xs font-semibold text-slate-600">
              Name
              <input
                required
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </label>
            <label className="block text-xs font-semibold text-slate-600">
              Slug
              <input
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                placeholder="auto from name"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
              />
            </label>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block text-xs font-semibold text-slate-600">
              Line
              <input
                required
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={line}
                onChange={(e) => setLine(e.target.value)}
              />
            </label>
            <label className="block text-xs font-semibold text-slate-600">
              Sort order
              <input
                type="number"
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={sortOrder}
                onChange={(e) => setSortOrder(Number(e.target.value) || 0)}
              />
            </label>
          </div>

          <label className="block text-xs font-semibold text-slate-600">
            Hero image URL (optional)
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              placeholder="https://..."
              value={heroExternalUrl}
              onChange={(e) => setHeroExternalUrl(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Description
            <textarea
              required
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Match terms (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-mono text-xs"
              value={matchTermsInput}
              onChange={(e) => setMatchTermsInput(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Best time
            <textarea
              required
              rows={2}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={bestTime}
              onChange={(e) => setBestTime(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Tips (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={tipsInput}
              onChange={(e) => setTipsInput(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Cost estimate
            <textarea
              required
              rows={2}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={costEstimate}
              onChange={(e) => setCostEstimate(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Bullets (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={bulletsInput}
              onChange={(e) => setBulletsInput(e.target.value)}
            />
          </label>

          <div className="flex flex-wrap gap-2 pt-2">
            <Button type="submit" disabled={saving}>
              {saving ? "Saving…" : editingId ? "Save changes" : "Create destination"}
            </Button>
            <Button type="button" variant="secondary" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
