"use client";

import { useMutation, useQuery } from "convex/react";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { toUserFacingErrorMessage } from "@/lib/userFriendlyError";
import { BulkUploadModal } from "@/components/admin/BulkUploadModal";
import { asNumber, asString, asStringArray } from "@/lib/bulkUpload/coerce";
import { importInBatches } from "@/lib/bulkUpload/importInBatches";

type DestinationRow = {
  _id: Id<"destinations">;
  slug: string;
  name: string;
  line: string;
  description: string;
  heroStorageId?: Id<"_storage">;
  heroExternalUrl?: string;
  heroUrl?: string;
  matchTerms: string[];
  bestTime: string;
  tips: string[];
  costEstimate: string;
  bullets: string[];
  sortOrder: number;
  autoGenerated: boolean;
  tourCount: number;
};

function toLines(v: string[]): string {
  return v.join("\n");
}

function fromLines(v: string): string[] {
  return v
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

export function AdminDestinationsPanel() {
  const rows = useQuery(api.destinations.listForAdmin, {});
  const seedDestinations = useMutation(api.destinations.seedDefaults);
  const createDestination = useMutation(api.destinations.createDestination);
  const updateDestination = useMutation(api.destinations.updateDestination);
  const deleteDestination = useMutation(api.destinations.deleteDestination);
  const bulkUpsert = useMutation(api.destinations.bulkUpsert);
  const generateHeroUploadUrl = useMutation(api.destinations.generateDestinationHeroUploadUrl);

  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<Id<"destinations"> | null>(null);

  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [line, setLine] = useState("");
  const [description, setDescription] = useState("");
  // `undefined` = leave hero unchanged; `null` = remove it; an id = a newly uploaded image.
  const [heroStorageId, setHeroStorageId] = useState<Id<"_storage"> | null | undefined>(undefined);
  const [heroPreviewUrl, setHeroPreviewUrl] = useState<string | null>(null);
  const [heroUploading, setHeroUploading] = useState(false);
  const [sortOrder, setSortOrder] = useState(100);
  const [matchTermsInput, setMatchTermsInput] = useState("");
  const [bestTime, setBestTime] = useState("");
  const [tipsInput, setTipsInput] = useState("");
  const [costEstimate, setCostEstimate] = useState("");
  const [bulletsInput, setBulletsInput] = useState("");

  const [msg, setMsg] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [bulkOpen, setBulkOpen] = useState(false);

  const list = useMemo(() => (rows ?? []) as DestinationRow[], [rows]);

  function resetForm() {
    setName("");
    setSlug("");
    setLine("");
    setDescription("");
    setHeroStorageId(undefined);
    setHeroPreviewUrl(null);
    setSortOrder(100);
    setMatchTermsInput("");
    setBestTime("");
    setTipsInput("");
    setCostEstimate("");
    setBulletsInput("");
  }

  function openNew() {
    setEditingId(null);
    resetForm();
    setMsg(null);
    setModalOpen(true);
  }

  function openEdit(d: DestinationRow) {
    setEditingId(d._id);
    setName(d.name);
    setSlug(d.slug);
    setLine(d.line);
    setDescription(d.description);
    setHeroStorageId(undefined);
    setHeroPreviewUrl(d.heroStorageId || d.heroExternalUrl ? d.heroUrl ?? null : null);
    setSortOrder(d.sortOrder);
    setMatchTermsInput(toLines(d.matchTerms));
    setBestTime(d.bestTime);
    setTipsInput(toLines(d.tips));
    setCostEstimate(d.costEstimate);
    setBulletsInput(toLines(d.bullets));
    setMsg(null);
    setModalOpen(true);
  }

  async function onPickHero(e: React.ChangeEvent<HTMLInputElement>) {
    const input = e.target;
    const file = input.files?.[0];
    input.value = "";
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      setMsg("Please choose an image file.");
      return;
    }
    const blobUrl = URL.createObjectURL(file);
    setHeroPreviewUrl(blobUrl);
    setHeroUploading(true);
    setMsg(null);
    try {
      const postUrl = await generateHeroUploadUrl({});
      const res = await fetch(postUrl, {
        method: "POST",
        headers: { "Content-Type": file.type || "image/jpeg" },
        body: file,
      });
      if (!res.ok) throw new Error(`Upload failed (${res.status})`);
      const data = (await res.json()) as { storageId?: Id<"_storage"> };
      if (!data.storageId) throw new Error("No storageId returned");
      setHeroStorageId(data.storageId);
    } catch (err) {
      URL.revokeObjectURL(blobUrl);
      setHeroPreviewUrl(null);
      setMsg(toUserFacingErrorMessage(err));
    } finally {
      setHeroUploading(false);
    }
  }

  function onRemoveHero() {
    setHeroStorageId(null);
    setHeroPreviewUrl(null);
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (heroUploading) {
      setMsg("Wait for the image upload to finish before saving.");
      return;
    }
    setSaving(true);
    setMsg(null);

    const base = {
      name,
      slug: slug.trim() || undefined,
      line,
      description,
      sortOrder,
      matchTerms: fromLines(matchTermsInput),
      bestTime,
      tips: fromLines(tipsInput),
      costEstimate,
      bullets: fromLines(bulletsInput),
    };

    try {
      if (editingId) {
        await updateDestination({ destinationId: editingId, ...base, heroStorageId });
        setMsg("Destination updated.");
      } else {
        await createDestination({ ...base, heroStorageId: heroStorageId ?? undefined });
        setMsg("Destination created.");
      }
      setModalOpen(false);
    } catch (err) {
      setMsg(toUserFacingErrorMessage(err));
    } finally {
      setSaving(false);
    }
  }

  if (rows === undefined) {
    return <p className="text-sm text-brand-muted">Loading…</p>;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Button type="button" variant="primary" onClick={openNew}>
          <Plus className="h-4 w-4" aria-hidden />
          Add destination
        </Button>
        <Button type="button" variant="secondary" onClick={() => setBulkOpen(true)}>
          Bulk upload
        </Button>
        <Button type="button" variant="secondary" onClick={() => void seedDestinations({})}>
          Seed sample destinations
        </Button>
        {msg && !modalOpen ? (
          <span className="text-sm text-brand-muted">{msg}</span>
        ) : null}
      </div>

      <div className="overflow-x-auto rounded-xl border border-slate-200/90 bg-white shadow-sm">
        <table className="min-w-[760px] w-full text-left text-sm">
          <thead className="whitespace-nowrap border-b border-slate-200 bg-slate-50/90 text-xs font-semibold uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-4 py-3">Name</th>
              <th className="px-4 py-3">Slug</th>
              <th className="px-4 py-3">Order</th>
              <th className="px-4 py-3">Tours</th>
              <th className="px-4 py-3">Source</th>
              <th className="px-4 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {list.map((d) => (
              <tr key={d._id} className="border-b border-slate-100 last:border-0">
                <td className="px-4 py-3 font-medium text-brand-ink">{d.name}</td>
                <td className="px-4 py-3 text-slate-600">/{d.slug}</td>
                <td className="px-4 py-3 text-slate-600">{d.sortOrder}</td>
                <td className="px-4 py-3 text-slate-600">{d.tourCount}</td>
                <td className="px-4 py-3">
                  <span
                    className={d.autoGenerated
                      ? "rounded-full bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-900"
                      : "rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-900"}
                  >
                    {d.autoGenerated ? "Auto" : "Manual"}
                  </span>
                </td>
                <td className="px-4 py-3 text-right">
                  <div className="flex flex-wrap justify-end gap-1">
                    <button
                      type="button"
                      className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-brand-primary hover:bg-slate-50"
                      onClick={() => openEdit(d)}
                    >
                      <Pencil className="h-3.5 w-3.5" aria-hidden />
                      Edit
                    </button>
                    <button
                      type="button"
                      className="inline-flex items-center gap-1 text-xs font-semibold text-red-600 hover:underline"
                      onClick={() => {
                        if (confirm("Delete this destination? Tours assigned to it will be unassigned.")) {
                          void deleteDestination({ destinationId: d._id });
                        }
                      }}
                    >
                      <Trash2 className="h-3.5 w-3.5" aria-hidden />
                      Delete
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {list.length === 0 ? (
          <p className="p-6 text-sm text-slate-500">No destinations yet.</p>
        ) : null}
      </div>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editingId ? "Edit destination" : "Add destination"}
        description="Manage destination details and matching terms used by destination pages."
        panelClassName="max-w-2xl"
        fullscreenOnMobile
      >
        <form onSubmit={onSubmit} className="space-y-3">
          {msg && modalOpen ? (
            <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900">
              {msg}
            </p>
          ) : null}

          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block text-xs font-semibold text-slate-600">
              Name
              <input
                required
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </label>
            <label className="block text-xs font-semibold text-slate-600">
              Slug
              <input
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                placeholder="auto from name"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
              />
            </label>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block text-xs font-semibold text-slate-600">
              Line
              <input
                required
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={line}
                onChange={(e) => setLine(e.target.value)}
              />
            </label>
            <label className="block text-xs font-semibold text-slate-600">
              Sort order
              <input
                type="number"
                className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
                value={sortOrder}
                onChange={(e) => setSortOrder(Number(e.target.value) || 0)}
              />
            </label>
          </div>

          <div className="text-xs font-semibold text-slate-600">
            Hero image (optional)
            <div className="mt-2 flex flex-wrap items-center gap-3">
              <div className="relative h-16 w-24 shrink-0 overflow-hidden rounded-lg border border-slate-200 bg-slate-100">
                {heroPreviewUrl ? (
                  /* eslint-disable-next-line @next/next/no-img-element -- blob + Convex URLs */
                  <img src={heroPreviewUrl} alt="" className="h-full w-full object-cover" />
                ) : (
                  <div className="flex h-full items-center justify-center px-1 text-center text-[10px] font-medium text-slate-500">
                    No image
                  </div>
                )}
              </div>
              <label className="inline-flex cursor-pointer items-center rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-brand-primary hover:bg-slate-50">
                <input
                  type="file"
                  accept="image/*"
                  className="sr-only"
                  disabled={heroUploading}
                  onChange={(e) => void onPickHero(e)}
                />
                {heroUploading ? "Uploading…" : heroPreviewUrl ? "Replace image" : "Upload image"}
              </label>
              {heroPreviewUrl ? (
                <button
                  type="button"
                  className="text-xs font-semibold text-red-600 hover:underline"
                  onClick={onRemoveHero}
                >
                  Remove
                </button>
              ) : null}
            </div>
          </div>

          <label className="block text-xs font-semibold text-slate-600">
            Description
            <textarea
              required
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Match terms (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-mono text-xs"
              value={matchTermsInput}
              onChange={(e) => setMatchTermsInput(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Best time
            <textarea
              required
              rows={2}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={bestTime}
              onChange={(e) => setBestTime(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Tips (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={tipsInput}
              onChange={(e) => setTipsInput(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Cost estimate
            <textarea
              required
              rows={2}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={costEstimate}
              onChange={(e) => setCostEstimate(e.target.value)}
            />
          </label>

          <label className="block text-xs font-semibold text-slate-600">
            Bullets (one per line)
            <textarea
              rows={3}
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
              value={bulletsInput}
              onChange={(e) => setBulletsInput(e.target.value)}
            />
          </label>

          <div className="flex flex-wrap gap-2 pt-2">
            <Button type="submit" disabled={saving}>
              {saving ? "Saving…" : editingId ? "Save changes" : "Create destination"}
            </Button>
            <Button type="button" variant="secondary" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
          </div>
        </form>
      </Modal>

      <BulkUploadModal
        open={bulkOpen}
        onClose={() => setBulkOpen(false)}
        title="Bulk upload destinations"
        description="Upload a .json or .xlsx file. Rows are upserted by slug (or slugified from name)."
        templateHint={
          <div className="space-y-1">
            <p className="font-semibold">Columns / keys</p>
            <p className="font-mono text-xs">
              slug, name, line, description, heroExternalUrl, matchTerms, bestTime, tips, costEstimate, bullets, sortOrder
            </p>
            <p className="text-xs text-slate-600">
              For XLSX, you can put multi-values as newline or comma-separated text.
            </p>
          </div>
        }
        transformRow={(row) => {
          const name = asString(row.name);
          const line = asString(row.line);
          const description = asString(row.description);
          const bestTime = asString(row.bestTime);
          const costEstimate = asString(row.costEstimate);
          const matchTerms = asStringArray(row.matchTerms) ?? [];
          const tips = asStringArray(row.tips) ?? [];
          const bullets = asStringArray(row.bullets) ?? [];
          if (!name) throw new Error("Missing name");
          if (!line) throw new Error("Missing line");
          if (!description) throw new Error("Missing description");
          if (!bestTime) throw new Error("Missing bestTime");
          if (!costEstimate) throw new Error("Missing costEstimate");
          return {
            slug: asString(row.slug),
            name,
            line,
            description,
            heroExternalUrl: asString(row.heroExternalUrl),
            matchTerms,
            bestTime,
            tips,
            costEstimate,
            bullets,
            sortOrder: asNumber(row.sortOrder),
          };
        }}
        onImport={async (rows) => {
          return await importInBatches({
            rows,
            batchSize: 25,
            importBatch: async (batch) => bulkUpsert({ rows: batch }),
            merge: (a, b) => ({
              processed: a.processed + b.processed,
              created: (a.created ?? 0) + (b.created ?? 0),
              updated: (a.updated ?? 0) + (b.updated ?? 0),
              skipped: (a.skipped ?? 0) + (b.skipped ?? 0),
              errors: [...(a.errors ?? []), ...(b.errors ?? [])],
            }),
          });
        }}
      />
    </div>
  );
}
