"use client";

import { useMutation } from "convex/react";
import { api } from "@convex/_generated/api";
import { useConvexSessionToken } from "@/hooks/useConvexSessionToken";
import type { Id } from "@convex/_generated/dataModel";
import { useMemo, useState } from "react";
import { Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { toUserFacingErrorMessage } from "@/lib/userFriendlyError";
import { useSafeQuery } from "@/hooks/useSafeQuery";
import { useEditorForm } from "@/hooks/useEditorForm";
import { confirmDiscard } from "@/hooks/useUnsavedChangesGuard";
import { QueryErrorBanner } from "@/components/admin/shared/EditorStatus";

type ProvinceRow = {
  _id: Id<"provinces">;
  slug: string;
  name: string;
  tagline: string;
  intro: string;
  heroExternalUrl?: string;
  bestTime: string;
  tips: string[];
  costEstimate: string;
  matchTerms: string[];
  sortOrder: number;
  autoGenerated?: boolean;
  tourCount: number;
  siteCount: number;
  destinationCount?: number;
};

type ProvinceForm = {
  name: string;
  tagline: string;
  intro: string;
  bestTime: string;
  tipsInput: string;
  costEstimate: string;
  matchTermsInput: string;
  sortOrder: string;
  showOnGuides: boolean;
};

const EMPTY_FORM: ProvinceForm = {
  name: "",
  tagline: "",
  intro: "",
  bestTime: "",
  tipsInput: "",
  costEstimate: "",
  matchTermsInput: "",
  sortOrder: "0",
  showOnGuides: true,
};

function fromLines(v: string): string[] {
  return v
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

function slugify(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, "-");
}

// Sensible defaults for the map/scrolly/palette fields the public /guides page
// needs but which aren't worth exposing as raw inputs to a non-technical admin
// adding a new province. They can be refined later directly in the data if needed.
const NEW_PROVINCE_VISUAL_DEFAULTS = {
  mapPointX: 500,
  mapPointY: 300,
  paletteFrom: "rgba(2, 6, 23, 0.92)",
  paletteVia: "rgba(56, 189, 248, 0.18)",
  paletteTo: "rgba(2, 6, 23, 0.92)",
  paletteAccent: "rgba(56, 189, 248, 0.95)",
} as const;

export function AdminProvincesPanel() {
  const sessionToken = useConvexSessionToken();
  const canMutate = typeof sessionToken === "string";
  const rowsQuery = useSafeQuery(
    api.provinces.listForAdmin,
    canMutate ? { sessionToken } : "skip",
  );
  const syncCatalog = useMutation(api.provinces.syncDefaultCatalog);
  const syncSites = useMutation(api.sites.syncDefaultCatalog);
  const createProvince = useMutation(api.provinces.createProvince);
  const updateProvince = useMutation(api.provinces.updateProvince);
  const deleteProvince = useMutation(api.provinces.deleteProvince);

  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<ProvinceRow | null>(null);
  const form = useEditorForm<ProvinceForm>(EMPTY_FORM);
  const { values, setField, dirty } = form;
  const [msg, setMsg] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [syncing, setSyncing] = useState(false);

  const list = useMemo(() => (rowsQuery.data ?? []) as ProvinceRow[], [rowsQuery.data]);

  function openNew() {
    setEditing(null);
    form.reset({ ...EMPTY_FORM, sortOrder: String(list.length) });
    setMsg(null);
    setModalOpen(true);
  }

  function openEdit(p: ProvinceRow) {
    setEditing(p);
    form.reset({
      name: p.name,
      tagline: p.tagline,
      intro: p.intro,
      bestTime: p.bestTime,
      tipsInput: p.tips.join("\n"),
      costEstimate: p.costEstimate,
      matchTermsInput: p.matchTerms.join(", "),
      sortOrder: String(p.sortOrder),
      showOnGuides: !p.autoGenerated,
    });
    setMsg(null);
    setModalOpen(true);
  }

  function closeEditor() {
    setModalOpen(false);
  }

  async function handleSave(e: React.FormEvent) {
    e.preventDefault();
    setMsg(null);
    const sortOrder = Number(values.sortOrder);
    if (values.sortOrder.trim() === "" || !Number.isFinite(sortOrder)) {
      setMsg("Sort order must be a number.");
      return;
    }
    const tips = fromLines(values.tipsInput);
    const matchTerms = values.matchTermsInput
      .split(",")
      .map((t) => t.trim().toLowerCase())
      .filter(Boolean);
    setSaving(true);
    try {
      if (!canMutate) throw new Error("Not authenticated");
      if (editing) {
        await updateProvince({
          sessionToken,
          provinceId: editing._id,
          name: values.name.trim(),
          tagline: values.tagline.trim(),
          intro: values.intro.trim(),
          bestTime: values.bestTime.trim(),
          tips,
          costEstimate: values.costEstimate.trim(),
          matchTerms,
          sortOrder,
          autoGenerated: !values.showOnGuides,
        });
        setMsg("Saved.");
      } else {
        const name = values.name.trim();
        const tagline = values.tagline.trim();
        await createProvince({
          sessionToken,
          slug: slugify(name),
          name,
          tagline,
          intro: values.intro.trim(),
          bestTime: values.bestTime.trim(),
          tips,
          costEstimate: values.costEstimate.trim(),
          matchTerms,
          sortOrder,
          mapPointX: NEW_PROVINCE_VISUAL_DEFAULTS.mapPointX,
          mapPointY: NEW_PROVINCE_VISUAL_DEFAULTS.mapPointY,
          mapPointLabel: name,
          scrollyEyebrow: tagline,
          scrollyTitle: `${name}: ${tagline}`,
          scrollyBullets: tips.slice(0, 3),
          paletteFrom: NEW_PROVINCE_VISUAL_DEFAULTS.paletteFrom,
          paletteVia: NEW_PROVINCE_VISUAL_DEFAULTS.paletteVia,
          paletteTo: NEW_PROVINCE_VISUAL_DEFAULTS.paletteTo,
          paletteAccent: NEW_PROVINCE_VISUAL_DEFAULTS.paletteAccent,
        });
        setMsg("Province created.");
      }
      form.markSaved();
      setModalOpen(false);
    } catch (err) {
      setMsg(toUserFacingErrorMessage(err));
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(p: ProvinceRow) {
    setMsg(null);
    if (p.siteCount > 0) {
      setMsg(
        `"${p.name}" still has ${p.siteCount} site(s). Move them to another province or delete them on the Sites page first.`,
      );
      return;
    }
    const destWarning =
      p.destinationCount && p.destinationCount > 0
        ? ` ${p.destinationCount} destination(s) link to this province and will lose their guide link.`
        : "";
    const ok = window.confirm(
      `Delete "${p.name}"?${destWarning} Tours assigned to it will be unassigned. This cannot be undone.`,
    );
    if (!ok) return;
    try {
      if (!canMutate) throw new Error("Not authenticated");
      await deleteProvince({ sessionToken, provinceId: p._id });
      setMsg("Province deleted.");
    } catch (err) {
      setMsg(toUserFacingErrorMessage(err));
    }
  }

  async function handleAddMissingDefaults() {
    const ok = window.confirm(
      "Add any missing default provinces and sites?\n\nExisting provinces and sites are never changed — only missing ones are added.",
    );
    if (!ok) return;
    setSyncing(true);
    setMsg(null);
    try {
      if (!canMutate) throw new Error("Not authenticated");
      const p = await syncCatalog({ sessionToken });
      const s = await syncSites({ sessionToken });
      setMsg(
        `Added ${p.created} province(s) and ${s.created} site(s). ` +
          `Left ${p.skipped} existing province(s) and ${s.alreadyPresent} existing site(s) unchanged.` +
          (s.skipped > 0 ? ` ${s.skipped} default site(s) skipped because their province doesn't exist.` : ""),
      );
    } catch (err) {
      setMsg(toUserFacingErrorMessage(err));
    } finally {
      setSyncing(false);
    }
  }

  return (
    <div className="space-y-6">
      <QueryErrorBanner error={rowsQuery.error} />
      <div className="flex flex-wrap items-center gap-3">
        <Button type="button" variant="primary" onClick={openNew}>
          <Plus className="mr-1 h-4 w-4" aria-hidden />
          Add province
        </Button>
        <Button
          type="button"
          variant="secondary"
          onClick={() => void handleAddMissingDefaults()}
          disabled={syncing}
        >
          <RefreshCw className="mr-2 h-4 w-4" />
          {syncing ? "Adding…" : "Add missing default provinces & sites"}
        </Button>
        {msg && !modalOpen ? <p className="text-sm text-slate-600">{msg}</p> : null}
      </div>

      {rowsQuery.isLoading ? <p className="text-sm text-slate-500">Loading…</p> : null}

      <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">
        <table className="min-w-full text-sm">
          <thead className="whitespace-nowrap bg-slate-50 text-left text-xs uppercase text-slate-500">
            <tr>
              <th className="px-4 py-3">Province</th>
              <th className="px-4 py-3">Sites</th>
              <th className="px-4 py-3">Tours</th>
              <th className="px-4 py-3">Order</th>
              <th className="px-4 py-3" />
            </tr>
          </thead>
          <tbody>
            {list.map((p) => (
              <tr key={p._id} className="border-t border-slate-100">
                <td className="px-4 py-3">
                  <p className="font-semibold text-slate-900">
                    {p.name}
                    {p.autoGenerated ? (
                      <span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold uppercase text-amber-800">
                        Hidden (auto-created)
                      </span>
                    ) : null}
                  </p>
                  <p className="text-xs text-slate-500">/guides/{p.slug}</p>
                </td>
                <td className="px-4 py-3">{p.siteCount}</td>
                <td className="px-4 py-3">{p.tourCount}</td>
                <td className="px-4 py-3">{p.sortOrder}</td>
                <td className="px-4 py-3 text-right">
                  <button
                    type="button"
                    className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"
                    onClick={() => openEdit(p)}
                    aria-label={`Edit ${p.name}`}
                  >
                    <Pencil className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    className="rounded-lg p-2 text-red-600 hover:bg-red-50"
                    onClick={() => void handleDelete(p)}
                    aria-label={`Delete ${p.name}`}
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Modal
        open={modalOpen}
        onClose={closeEditor}
        confirmClose={dirty}
        title={editing ? "Edit province" : "Add province"}
      >
        <form onSubmit={(e) => void handleSave(e)} className="space-y-4">
          {msg && modalOpen ? (
            <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900">{msg}</p>
          ) : null}
          <label className="block text-xs font-semibold text-slate-600">
            Name
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.name}
              onChange={(e) => setField("name", e.target.value)}
              required
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Tagline
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.tagline}
              onChange={(e) => setField("tagline", e.target.value)}
              required
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Intro
            <textarea
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              rows={4}
              value={values.intro}
              onChange={(e) => setField("intro", e.target.value)}
              required
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Best time
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.bestTime}
              onChange={(e) => setField("bestTime", e.target.value)}
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Tips (one per line)
            <textarea
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              rows={3}
              value={values.tipsInput}
              onChange={(e) => setField("tipsInput", e.target.value)}
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Cost estimate
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.costEstimate}
              onChange={(e) => setField("costEstimate", e.target.value)}
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Match terms (comma-separated)
            <input
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.matchTermsInput}
              onChange={(e) => setField("matchTermsInput", e.target.value)}
            />
          </label>
          <label className="block text-xs font-semibold text-slate-600">
            Sort order
            <input
              type="number"
              className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"
              value={values.sortOrder}
              onChange={(e) => setField("sortOrder", e.target.value)}
              required
            />
          </label>
          {editing ? (
            <label className="flex items-center gap-2 text-sm text-slate-700">
              <input
                type="checkbox"
                checked={values.showOnGuides}
                onChange={(e) => setField("showOnGuides", e.target.checked)}
              />
              Show on public guides
              {editing.autoGenerated ? (
                <span className="text-xs text-slate-500">(auto-created from a tour — hidden until enabled)</span>
              ) : null}
            </label>
          ) : null}
          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="secondary"
              onClick={() => {
                if (confirmDiscard(dirty)) closeEditor();
              }}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={saving}>
              {saving ? "Saving…" : "Save"}
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
