import { expect, test } from "vitest";
import { api } from "../_generated/api.js";
import type { Id } from "../_generated/dataModel.js";
import { newTest, signIn } from "./helpers.test-utils.js";

const now = () => Date.now();

async function insertProvince(t: ReturnType<typeof newTest>, slug: string, name: string) {
  return await t.run(async (ctx) =>
    ctx.db.insert("provinces", {
      slug,
      name,
      tagline: "t",
      intro: "i",
      bestTime: "b",
      tips: [],
      costEstimate: "c",
      matchTerms: [],
      sortOrder: 0,
      mapPointX: 0,
      mapPointY: 0,
      mapPointLabel: name,
      scrollyEyebrow: "e",
      scrollyTitle: "s",
      scrollyBullets: [],
      paletteFrom: "a",
      paletteVia: "b",
      paletteTo: "c",
      paletteAccent: "d",
      createdAt: now(),
      updatedAt: now(),
    }),
  );
}

// ---------------------------------------------------------------- provinces/sites

test("syncDefaultCatalog never overwrites edited provinces or sites", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);

  const first = await t.mutation(api.provinces.syncDefaultCatalog, { sessionToken });
  expect(first.created).toBeGreaterThan(0);
  await t.mutation(api.sites.syncDefaultCatalog, { sessionToken });

  const sindh = await t.run(async (ctx) =>
    ctx.db.query("provinces").withIndex("by_slug", (q) => q.eq("slug", "sindh")).unique(),
  );
  await t.mutation(api.provinces.updateProvince, {
    sessionToken,
    provinceId: sindh!._id,
    tagline: "Admin-edited tagline",
    sortOrder: 42,
  });
  const site = await t.run(async (ctx) =>
    ctx.db
      .query("sites")
      .withIndex("by_province_and_slug", (q) =>
        q.eq("provinceId", sindh!._id).eq("slug", "mohenjo-daro"),
      )
      .unique(),
  );
  await t.mutation(api.sites.updateSite, {
    sessionToken,
    siteId: site!._id,
    city: "Admin City",
    isActive: false,
    featured: false,
  });

  const again = await t.mutation(api.provinces.syncDefaultCatalog, { sessionToken });
  expect(again.created).toBe(0);
  expect(again.updated).toBe(0);
  const sitesAgain = await t.mutation(api.sites.syncDefaultCatalog, { sessionToken });
  expect(sitesAgain.created).toBe(0);
  expect(sitesAgain.updated).toBe(0);

  const p = await t.run(async (ctx) => ctx.db.get(sindh!._id));
  expect(p!.tagline).toBe("Admin-edited tagline");
  expect(p!.sortOrder).toBe(42);
  const s = await t.run(async (ctx) => ctx.db.get(site!._id));
  expect(s!.city).toBe("Admin City");
  expect(s!.isActive).toBe(false);
  expect(s!.featured).toBe(false);
});

test("deleteProvince refuses while sites exist and never cascades", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const provinceId = await insertProvince(t, "p1", "P1");
  const siteId = await t.mutation(api.sites.createSite, {
    sessionToken,
    provinceId,
    slug: "s1",
    name: "S1",
    type: "historical",
    summary: "",
    history: "",
    featured: false,
    sortOrder: 0,
    isActive: true,
  });

  await expect(
    t.mutation(api.provinces.deleteProvince, { sessionToken, provinceId }),
  ).rejects.toThrow(/site/);
  expect(await t.run(async (ctx) => ctx.db.get(siteId))).not.toBeNull();
  expect(await t.run(async (ctx) => ctx.db.get(provinceId))).not.toBeNull();

  // Move the site elsewhere, then delete succeeds.
  const other = await insertProvince(t, "p2", "P2");
  await t.mutation(api.sites.updateSite, { sessionToken, siteId, provinceId: other });
  await t.mutation(api.provinces.deleteProvince, { sessionToken, provinceId });
  expect(await t.run(async (ctx) => ctx.db.get(provinceId))).toBeNull();
  expect((await t.run(async (ctx) => ctx.db.get(siteId)))!.provinceId).toBe(other);
});

test("updateProvince can publish an auto-generated province", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const provinceId = await insertProvince(t, "auto", "Auto");
  await t.run(async (ctx) => ctx.db.patch(provinceId, { autoGenerated: true }));
  expect(await t.query(api.provinces.listSlugs, {})).not.toContain("auto");
  await t.mutation(api.provinces.updateProvince, {
    sessionToken,
    provinceId,
    autoGenerated: false,
  });
  expect(await t.query(api.provinces.listSlugs, {})).toContain("auto");
});

test("sites: null clears city; bulk import blanks never wipe or republish", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  await insertProvince(t, "p1", "P1");
  await t.mutation(api.sites.bulkUpsert, {
    sessionToken,
    rows: [
      {
        provinceSlug: "p1",
        slug: "fort",
        name: "Fort",
        type: "historical",
        summary: "Summary",
        history: "History",
        city: "Lahore",
        era: "Mughal",
        heroExternalUrl: "https://x/y.jpg",
        destinationSlug: "lahore",
        featured: true,
        sortOrder: 3,
        isActive: false,
      },
    ],
  });
  // Re-import with blank optional cells and no isActive.
  const res = await t.mutation(api.sites.bulkUpsert, {
    sessionToken,
    rows: [
      {
        provinceSlug: "p1",
        slug: "fort",
        name: "Fort renamed",
        type: "historical",
        summary: "",
        history: "",
        city: "",
        era: "",
      },
    ],
  });
  expect(res.errors).toEqual([]);
  const site = await t.run(async (ctx) =>
    ctx.db.query("sites").filter((q) => q.eq(q.field("slug"), "fort")).unique(),
  );
  expect(site!.name).toBe("Fort renamed");
  expect(site!.summary).toBe("Summary");
  expect(site!.city).toBe("Lahore");
  expect(site!.era).toBe("Mughal");
  expect(site!.heroExternalUrl).toBe("https://x/y.jpg");
  expect(site!.destinationSlug).toBe("lahore");
  expect(site!.featured).toBe(true);
  expect(site!.sortOrder).toBe(3);
  expect(site!.isActive).toBe(false);

  await t.mutation(api.sites.updateSite, { sessionToken, siteId: site!._id, city: null });
  expect((await t.run(async (ctx) => ctx.db.get(site!._id)))!.city).toBeUndefined();
});

// ---------------------------------------------------------------- blog

test("blog: slug uniqueness, clearable meta, bulk blanks keep meta, dupes don't crash readers", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const a = await t.mutation(api.blog.createPost, {
    sessionToken,
    title: "A",
    slug: "Same Slug",
    content: "x",
    metaTitle: "Meta A",
    metaDescription: "Desc A",
    published: true,
  });
  await expect(
    t.mutation(api.blog.createPost, {
      sessionToken,
      title: "B",
      slug: "same-slug",
      content: "y",
      published: false,
    }),
  ).rejects.toThrow(/already uses/);
  const b = await t.mutation(api.blog.createPost, {
    sessionToken,
    title: "B",
    slug: "other",
    content: "y",
    published: false,
  });
  await expect(
    t.mutation(api.blog.updatePost, { sessionToken, postId: b, slug: "same-slug" }),
  ).rejects.toThrow(/already uses/);
  // Saving a post with its own unchanged slug is fine.
  await t.mutation(api.blog.updatePost, { sessionToken, postId: a, slug: "same-slug", title: "A2" });

  // Bulk import with blank meta keeps existing SEO text.
  const bulk = await t.mutation(api.blog.bulkUpsert, {
    sessionToken,
    rows: [{ title: "A3", slug: "same-slug", content: "z", metaTitle: "", published: true }],
  });
  expect(bulk.errors).toEqual([]);
  let post = await t.run(async (ctx) => ctx.db.get(a));
  expect(post!.title).toBe("A3");
  expect(post!.metaTitle).toBe("Meta A");
  expect(post!.metaDescription).toBe("Desc A");

  // Editor can clear meta with null.
  await t.mutation(api.blog.updatePost, {
    sessionToken,
    postId: a,
    metaTitle: null,
    metaDescription: null,
  });
  post = await t.run(async (ctx) => ctx.db.get(a));
  expect(post!.metaTitle).toBeUndefined();
  expect(post!.metaDescription).toBeUndefined();

  // Legacy duplicate slugs don't break the public reader.
  await t.run(async (ctx) =>
    ctx.db.insert("blogPosts", {
      title: "Dupe",
      slug: "same-slug",
      content: "d",
      published: false,
      createdAt: now(),
    }),
  );
  const found = await t.query(api.blog.getPostBySlug, { slug: "same-slug" });
  expect(found!._id).toBe(a);

  const page = await t.query(api.blog.listAdminPage, {
    sessionToken,
    paginationOpts: { numItems: 2, cursor: null },
  });
  expect(page.page.length).toBe(2);
  expect(page.isDone).toBe(false);
});

// ---------------------------------------------------------------- faqs

test("faqs: bulk update with blank sortOrder/isActive/category succeeds and preserves values", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const id = await t.mutation(api.faqs.upsert, {
    sessionToken,
    question: "Q1",
    answer: "A1",
    category: "Visas",
    sortOrder: 7,
    isActive: false,
  });
  const res = await t.mutation(api.faqs.bulkUpsert, {
    sessionToken,
    rows: [{ faqId: id, question: "Q1", answer: "A1 updated" }],
  });
  expect(res.errors).toEqual([]);
  expect(res.updated).toBe(1);
  const row = await t.run(async (ctx) => ctx.db.get(id));
  expect(row!.answer).toBe("A1 updated");
  expect(row!.sortOrder).toBe(7);
  expect(row!.isActive).toBe(false);
  expect(row!.category).toBe("Visas");

  // Matching by category+question also works.
  const res2 = await t.mutation(api.faqs.bulkUpsert, {
    sessionToken,
    rows: [{ question: "q1", answer: "A1 v3", category: "Visas" }],
  });
  expect(res2.updated).toBe(1);
  expect((await t.run(async (ctx) => ctx.db.get(id)))!.answer).toBe("A1 v3");

  // upsert without category keeps the category.
  await t.mutation(api.faqs.upsert, { sessionToken, faqId: id, question: "Q1", answer: "A4" });
  expect((await t.run(async (ctx) => ctx.db.get(id)))!.category).toBe("Visas");

  const page = await t.query(api.faqs.listAdminPage, {
    sessionToken,
    paginationOpts: { numItems: 10, cursor: null },
  });
  expect(page.page.map((f) => f._id)).toContain(id);
});

// ---------------------------------------------------------------- about

async function seedAbout(t: ReturnType<typeof newTest>, sessionToken: string) {
  await t.mutation(api.about.upsertAdmin, {
    sessionToken,
    eyebrow: "e",
    heading: "h",
    exploreTitle: "x",
    exploreBodyText: "x",
    missionTitle: "m",
    missionBodyText: "m",
    visionTitle: "v",
    visionBodyText: "v",
    stats: [],
  });
}

test("about: partners get stable ids and removal targets the right partner", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  await seedAbout(t, sessionToken);
  // Legacy partners without ids.
  await t.run(async (ctx) => {
    const row = await ctx.db.query("aboutPageSettings").unique();
    await ctx.db.patch(row!._id, {
      partners: [{ name: "Legacy A" }, { name: "Legacy B" }],
    });
  });
  const cId = await t.mutation(api.about.addPartner, { sessionToken, name: "C" });
  let partners = (await t.query(api.about.getAdmin, { sessionToken }))!.partners;
  expect(partners.map((p) => p.name)).toEqual(["Legacy A", "Legacy B", "C"]);
  expect(partners.every((p) => typeof p.id === "string")).toBe(true);

  // Stale index guard: index 0 is no longer "Legacy B".
  await expect(
    t.mutation(api.about.removePartner, { sessionToken, index: 0, expectedName: "Legacy B" }),
  ).rejects.toThrow(/changed/);

  await t.mutation(api.about.removePartner, { sessionToken, partnerId: partners[1]!.id });
  partners = (await t.query(api.about.getAdmin, { sessionToken }))!.partners;
  expect(partners.map((p) => p.name)).toEqual(["Legacy A", "C"]);
  expect(partners[1]!.id).toBe(cId);

  // Legacy index-only call still works.
  await t.mutation(api.about.removePartner, { sessionToken, index: 0 });
  partners = (await t.query(api.about.getAdmin, { sessionToken }))!.partners;
  expect(partners.map((p) => p.name)).toEqual(["C"]);
});

test("about: adding past the partner cap errors instead of silently dropping", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  await seedAbout(t, sessionToken);
  for (let i = 0; i < 20; i++) {
    await t.mutation(api.about.addPartner, { sessionToken, name: `P${i}` });
  }
  await expect(
    t.mutation(api.about.addPartner, { sessionToken, name: "P20" }),
  ).rejects.toThrow(/at most/);
});

// ---------------------------------------------------------------- team

test("team: move works with tied sortOrders and bulk blanks keep values", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const ids: Id<"teamMembers">[] = [];
  await t.run(async (ctx) => {
    for (const name of ["A", "B", "C"]) {
      ids.push(
        await ctx.db.insert("teamMembers", {
          name,
          role: "r",
          sortOrder: 10,
          isActive: false,
          createdAt: now(),
          updatedAt: now(),
        }),
      );
    }
  });
  const before = await t.query(api.team.listForAdmin, { sessionToken });
  const second = before[1]!;
  await t.mutation(api.team.move, { sessionToken, id: second._id, direction: "up" });
  const after = await t.query(api.team.listForAdmin, { sessionToken });
  expect(after[0]!._id).toBe(second._id);
  expect(new Set(after.map((r) => r.sortOrder)).size).toBe(3);

  await t.mutation(api.team.bulkUpsert, {
    sessionToken,
    rows: [{ name: "A", role: "r" }],
  });
  const a = await t.run(async (ctx) => ctx.db.get(ids[0]!));
  expect(a!.isActive).toBe(false);
});
