import { expect, test } from "vitest";
import { api, internal } from "../_generated/api.js";
import type { Id } from "../_generated/dataModel.js";
import { newTest, signIn } from "./helpers.test-utils.js";

type T = ReturnType<typeof newTest>;

function destinationRow(overrides: Record<string, unknown> = {}) {
  return {
    slug: "hunza",
    name: "Hunza",
    line: "Forts & Karakoram culture.",
    description: "Admin-written description.",
    matchTerms: ["hunza"],
    bestTime: "Spring",
    tips: ["Carry layers"],
    costEstimate: "Varies",
    bullets: ["Eagle's Nest"],
    autoGenerated: false,
    sortOrder: 3,
    createdAt: 1,
    updatedAt: 1,
    ...overrides,
  };
}

async function insertDestination(t: T, overrides: Record<string, unknown> = {}) {
  return (await t.run((ctx) =>
    ctx.db.insert("destinations", destinationRow(overrides) as never),
  )) as Id<"destinations">;
}

const tourArgs = {
  title: "Trip",
  slug: "trip",
  description: "A trip.",
  durationDays: 3,
  location: "Hunza",
  images: ["https://img.example/tour-cover.jpg"],
  itinerary: [{ day: 1, title: "Day 1", description: "Go" }],
  isActive: true,
};

test("admin edits take ownership of an auto-generated destination", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await insertDestination(t, { autoGenerated: true });
  await t.mutation(api.destinations.updateDestination, {
    sessionToken,
    destinationId,
    description: "Hand-written by the admin.",
  });
  const d = await t.run((ctx) => ctx.db.get(destinationId));
  expect(d!.autoGenerated).toBe(false);

  // Late AI enrichment must not overwrite the admin's text.
  await t.mutation(internal.destinations.applyAutoEnrichment, {
    destinationId,
    tourId: (await t.run((ctx) =>
      ctx.db.insert("tours", { ...tourArgs, createdAt: 1 }),
    )) as Id<"tours">,
    description: "AI text",
  });
  const after = await t.run((ctx) => ctx.db.get(destinationId));
  expect(after!.description).toBe("Hand-written by the admin.");
});

test("removing a hero clears both the uploaded and the external image", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await insertDestination(t, {
    heroExternalUrl: "https://img.example/hero.jpg",
  });
  await t.mutation(api.destinations.updateDestination, {
    sessionToken,
    destinationId,
    heroStorageId: null,
  });
  const d = await t.run((ctx) => ctx.db.get(destinationId));
  expect(d!.heroExternalUrl).toBeUndefined();
  expect(d!.heroStorageId).toBeUndefined();
});

test("tour saves never replace an existing destination hero", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await insertDestination(t, {
    autoGenerated: true,
    heroExternalUrl: "https://img.example/chosen-hero.jpg",
  });
  await t.mutation(api.tours.createTour, {
    sessionToken,
    ...tourArgs,
    destinationIds: [destinationId],
  });
  const d = await t.run((ctx) => ctx.db.get(destinationId));
  expect(d!.heroExternalUrl).toBe("https://img.example/chosen-hero.jpg");
});

test("auto-create does not duplicate an existing destination with the same name", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  // Existing destination whose match terms don't cover the tour's location text.
  await insertDestination(t, { slug: "skardu", name: "Skardu", matchTerms: ["zz"] });
  await t.mutation(api.tours.createTour, {
    sessionToken,
    ...tourArgs,
    location: "Skardu",
  });
  const all = await t.run((ctx) => ctx.db.query("destinations").collect());
  expect(all.map((d) => d.slug)).toEqual(["skardu"]);
});

test("AI enrichment never creates provinces or replaces a tour's provinces", async () => {
  const t = newTest();
  const destinationId = await insertDestination(t, { autoGenerated: true });
  const provinceBase = {
    tagline: "t",
    intro: "i",
    bestTime: "b",
    tips: [],
    costEstimate: "c",
    matchTerms: [],
    sortOrder: 0,
    mapPointX: 0,
    mapPointY: 0,
    mapPointLabel: "m",
    scrollyEyebrow: "e",
    scrollyTitle: "s",
    scrollyBullets: [],
    paletteFrom: "a",
    paletteVia: "b",
    paletteTo: "c",
    paletteAccent: "d",
    createdAt: 1,
    updatedAt: 1,
  };
  const curated = await t.run((ctx) =>
    ctx.db.insert("provinces", { ...provinceBase, slug: "gilgit-baltistan", name: "GB" }),
  );
  const tourId = (await t.run((ctx) =>
    ctx.db.insert("tours", { ...tourArgs, createdAt: 1 }),
  )) as Id<"tours">;

  await t.mutation(internal.destinations.applyAutoEnrichment, {
    destinationId,
    tourId,
    provinceSlug: "made-up-province",
    provinceName: "Made Up",
  });
  const provinces = await t.run((ctx) => ctx.db.query("provinces").collect());
  expect(provinces).toHaveLength(1);
  expect((await t.run((ctx) => ctx.db.get(tourId)))!.provinceIds).toBeUndefined();

  await t.mutation(internal.destinations.applyAutoEnrichment, {
    destinationId,
    tourId,
    provinceSlug: "gilgit-baltistan",
  });
  expect((await t.run((ctx) => ctx.db.get(tourId)))!.provinceIds).toEqual([curated]);
});

test("bulk destination import keeps sort order and hero when columns are blank", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await insertDestination(t, {
    heroExternalUrl: "https://img.example/hero.jpg",
    sortOrder: 3,
  });
  await t.mutation(api.destinations.bulkUpsert, {
    sessionToken,
    rows: [
      {
        slug: "hunza",
        name: "Hunza Valley",
        line: "New line",
        description: "New description",
        matchTerms: [],
        bestTime: "Summer",
        tips: [],
        costEstimate: "Budget",
        bullets: [],
      },
    ],
  });
  const d = await t.run((ctx) => ctx.db.get(destinationId));
  expect(d!.name).toBe("Hunza Valley");
  expect(d!.sortOrder).toBe(3);
  expect(d!.heroExternalUrl).toBe("https://img.example/hero.jpg");
  expect(d!.tips).toEqual(["Carry layers"]);
  expect(d!.matchTerms).toEqual(["hunza"]);
});

test("syncDefaultCatalog only inserts missing defaults", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await insertDestination(t, {
    description: "Admin-written description.",
  });
  await t.mutation(api.destinations.syncDefaultCatalog, { sessionToken });
  const d = await t.run((ctx) => ctx.db.get(destinationId));
  expect(d!.description).toBe("Admin-written description.");
  expect(d!.sortOrder).toBe(3);
  const all = await t.run((ctx) => ctx.db.query("destinations").collect());
  expect(all.length).toBeGreaterThan(1);
});
