import { expect, test } from "vitest";
import { api } from "../_generated/api.js";
import type { Id } from "../_generated/dataModel.js";
import { newTest, signIn } from "./helpers.test-utils.js";

type T = ReturnType<typeof newTest>;

const baseTour = {
  title: "Hunza Explorer",
  slug: "hunza-explorer",
  description: "A week in Hunza.",
  durationDays: 7,
  location: "Hunza",
  images: ["https://img.example/a.jpg", "https://img.example/b.jpg"],
  itinerary: [{ day: 1, title: "Arrive", description: "Arrive in Hunza" }],
  isActive: true,
};

async function createTour(t: T, sessionToken: string, overrides: Record<string, unknown> = {}) {
  return (await t.mutation(api.tours.createTour, {
    sessionToken,
    ...baseTour,
    ...overrides,
  } as never)) as Id<"tours">;
}

test("review moderation never overwrites the admin's manual rating", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const tourId = await createTour(t, sessionToken, { ratingAvg: 4.9, reviewsCount: 120 });

  await t.mutation(api.tourReviews.submitReview, {
    tourId,
    authorName: "Ali",
    rating: 3,
    body: "Pretty good trip overall, thanks!",
  });
  const reviewId = await t.run(async (ctx) => {
    const r = await ctx.db.query("tourReviews").first();
    return r!._id;
  });
  await t.mutation(api.tourReviews.setReviewStatus, { sessionToken, reviewId, status: "approved" });

  let tour = await t.run((ctx) => ctx.db.get(tourId));
  expect(tour!.ratingAvg).toBe(4.9);
  expect(tour!.reviewsCount).toBe(120);
  expect(tour!.approvedReviewAvg).toBe(3);
  expect(tour!.approvedReviewCount).toBe(1);

  await t.mutation(api.tourReviews.deleteReview, { sessionToken, reviewId });
  tour = await t.run((ctx) => ctx.db.get(tourId));
  expect(tour!.ratingAvg).toBe(4.9);
  expect(tour!.reviewsCount).toBe(120);
  expect(tour!.approvedReviewCount).toBe(0);
  expect(tour!.approvedReviewAvg).toBeUndefined();
});

test("getTourForAdmin throws on auth failure instead of pretending the tour is missing", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const tourId = await createTour(t, sessionToken);

  await expect(
    t.query(api.tours.getTourForAdmin, { tourId, sessionToken: "expired-token" }),
  ).rejects.toThrow(/Not authenticated/);
  const customer = await signIn(t, "customer");
  await expect(
    t.query(api.tours.getTourForAdmin, { tourId, sessionToken: customer }),
  ).rejects.toThrow(/Admin access required/);

  const tour = await t.query(api.tours.getTourForAdmin, { tourId, sessionToken });
  expect(tour?._id).toBe(tourId);
  expect(typeof tour?.updatedAt).toBe("number");
});

test("legacy destinationId can be cleared with null", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await t.run((ctx) =>
    ctx.db.insert("destinations", {
      slug: "hunza",
      name: "Hunza",
      line: "l",
      description: "d",
      heroExternalUrl: "https://img.example/hero.jpg",
      matchTerms: ["hunza"],
      bestTime: "b",
      tips: [],
      costEstimate: "c",
      bullets: [],
      autoGenerated: false,
      sortOrder: 0,
      createdAt: 1,
      updatedAt: 1,
    }),
  );
  const tourId = await createTour(t, sessionToken, { destinationId });
  await t.mutation(api.tours.updateTour, {
    sessionToken,
    tourId,
    destinationIds: [],
    destinationId: null,
  } as never);
  const tour = await t.run((ctx) => ctx.db.get(tourId));
  expect(tour!.destinationId).toBeUndefined();
  expect(tour!.destinationIds).toEqual([]);

  // Older editors omit destinationId entirely when the list is emptied.
  const legacy = await createTour(t, sessionToken, { slug: "legacy", destinationId });
  await t.mutation(api.tours.updateTour, { sessionToken, tourId: legacy, destinationIds: [] });
  expect((await t.run((ctx) => ctx.db.get(legacy)))!.destinationId).toBeUndefined();
});

test("stale editor saves are rejected instead of silently overwriting", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const tourId = await createTour(t, sessionToken);
  const opened = await t.query(api.tours.getTourForAdmin, { tourId, sessionToken });

  // Another admin saves first.
  await t.mutation(api.tours.updateTour, {
    sessionToken,
    tourId,
    title: "Renamed by admin B",
    expectedUpdatedAt: opened!.updatedAt,
  } as never);

  await expect(
    t.mutation(api.tours.updateTour, {
      sessionToken,
      tourId,
      title: "Stale save by admin A",
      expectedUpdatedAt: opened!.updatedAt,
    } as never),
  ).rejects.toThrow(/changed by someone else/);

  const tour = await t.run((ctx) => ctx.db.get(tourId));
  expect(tour!.title).toBe("Renamed by admin B");
});

test("tour slugs stay unique and duplicates can't crash public reads", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const a = await createTour(t, sessionToken);
  await expect(createTour(t, sessionToken, { title: "Other" })).rejects.toThrow(
    /already used by another tour/,
  );
  const b = await createTour(t, sessionToken, { slug: "other-tour" });
  await expect(
    t.mutation(api.tours.updateTour, { sessionToken, tourId: b, slug: "Hunza Explorer" }),
  ).rejects.toThrow(/already used by another tour/);
  // Saving a tour with its own slug is fine.
  await t.mutation(api.tours.updateTour, { sessionToken, tourId: a, slug: "hunza-explorer" });

  // A pre-existing duplicate row must not break the public page.
  await t.run(async (ctx) => {
    const doc = await ctx.db.get(a);
    const { _id, _creationTime, ...rest } = doc!;
    void _id;
    void _creationTime;
    await ctx.db.insert("tours", rest);
  });
  const bySlug = await t.query(api.tours.getTourBySlug, { slug: "hunza-explorer" });
  expect(bySlug?.slug).toBe("hunza-explorer");
  const pricing = await t.query(api.tours.getTourPricingBySlug, { slug: "hunza-explorer" });
  expect(pricing).not.toBeNull();
});

test("bulk import update only patches the columns present in the row", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const destinationId = await t.run((ctx) =>
    ctx.db.insert("destinations", {
      slug: "hunza",
      name: "Hunza",
      line: "l",
      description: "d",
      heroExternalUrl: "https://img.example/hero.jpg",
      matchTerms: ["hunza"],
      bestTime: "b",
      tips: [],
      costEstimate: "c",
      bullets: [],
      autoGenerated: false,
      sortOrder: 0,
      createdAt: 1,
      updatedAt: 1,
    }),
  );
  const tourId = await createTour(t, sessionToken, {
    types: ["adventure"],
    destinationIds: [destinationId],
    pricePkr: 250000,
    priceUsd: 900,
    highlights: ["Eagle's Nest"],
  });

  // Spreadsheet row without images/types/price/destinations.
  await t.mutation(api.tours.bulkUpsert, {
    sessionToken,
    rows: [
      {
        title: "Hunza Explorer (2026)",
        slug: "hunza-explorer",
        description: "Updated description.",
        durationDays: 8,
        location: "Hunza",
        // The deployed bulk importer defaults a blank price cell to 0.
        price: 0,
        images: [],
        itinerary: [{ day: 1, title: "Arrive", description: "Arrive in Hunza" }],
        isActive: true,
      },
    ],
  } as never);

  const tour = await t.run((ctx) => ctx.db.get(tourId));
  expect(tour!.title).toBe("Hunza Explorer (2026)");
  expect(tour!.durationDays).toBe(8);
  expect(tour!.images).toEqual(baseTour.images);
  expect(tour!.types).toEqual(["adventure"]);
  expect(tour!.price).toBe(250000);
  expect(tour!.pricePkr).toBe(250000);
  expect(tour!.destinationIds).toEqual([destinationId]);
  expect(tour!.highlights).toEqual(["Eagle's Nest"]);
});

test("deleting a tour with bookings, reviews or itineraries is refused", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const withBooking = await createTour(t, sessionToken, { slug: "with-booking" });
  const withReview = await createTour(t, sessionToken, { slug: "with-review" });
  const withItinerary = await createTour(t, sessionToken, { slug: "with-itinerary" });
  const unused = await createTour(t, sessionToken, { slug: "unused" });

  await t.run(async (ctx) => {
    await ctx.db.insert("guestBookings", {
      name: "Guest",
      phone: "1",
      phoneNormalized: "1",
      tourId: withBooking,
      peopleCount: 2,
      status: "pending",
      createdAt: 1,
    });
    await ctx.db.insert("tourReviews", {
      tourId: withReview,
      authorName: "A",
      rating: 5,
      body: "Great tour!!",
      status: "pending",
      createdAt: 1,
    });
    await ctx.db.insert("itineraries", {
      title: "Plan",
      clientName: "Client",
      days: 3,
      theme: "minimal",
      status: "draft",
      sourceTourId: withItinerary,
      createdAt: 1,
      updatedAt: 1,
    } as never);
  });

  for (const tourId of [withBooking, withReview, withItinerary]) {
    await expect(t.mutation(api.tours.deleteTour, { sessionToken, tourId })).rejects.toThrow(
      /Deactivate/,
    );
    expect(await t.run((ctx) => ctx.db.get(tourId))).not.toBeNull();
  }

  await t.mutation(api.tours.deleteTour, { sessionToken, tourId: unused });
  expect(await t.run((ctx) => ctx.db.get(unused))).toBeNull();
});

test("tour update never re-creates a destination the admin deleted", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  const tourId = await createTour(t, sessionToken, { location: "Fairy Meadows" });
  const created = await t.run((ctx) => ctx.db.query("destinations").collect());
  expect(created).toHaveLength(1);

  await t.mutation(api.destinations.deleteDestination, {
    sessionToken,
    destinationId: created[0]!._id,
  });
  await t.mutation(api.tours.updateTour, { sessionToken, tourId, title: "Fairy Meadows trek" });
  const after = await t.run((ctx) => ctx.db.query("destinations").collect());
  expect(after).toHaveLength(0);
});

test("admin tour list is newest first and paginated", async () => {
  const t = newTest();
  const sessionToken = await signIn(t);
  for (let i = 0; i < 5; i++) {
    await createTour(t, sessionToken, { slug: `tour-${i}`, title: `Tour ${i}` });
  }
  const first = await t.query(api.tours.listToursForAdmin, {
    sessionToken,
    paginationOpts: { numItems: 2, cursor: null },
  });
  expect(first.page.map((r) => r.slug)).toEqual(["tour-4", "tour-3"]);
  expect(first.isDone).toBe(false);
});
